# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="campaignexecution",
            new_name="marketing_cam_sta_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="campaignexecution",
            new_name="marketing_sta_sch_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="campaignexecution",
            new_name="marketing_cre_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="marketing_tml_fir_sta_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="marketing_fir_tem_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="entitytag",
            new_name="marketing_tag_ent_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="entitytag",
            new_name="marketing_ent_ent_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="entitytag",
            new_name="marketing_app_app_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="segment",
            new_name="marketing_seg_fir_sta_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="segment",
            new_name="marketing_fir_cre_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="tag",
            new_name="marketing_fir_cat_idx",
            old_name="mkt_idx",
        ),
        migrations.RenameIndex(
            model_name="tag",
            new_name="marketing_fir_slu_idx",
            old_name="mkt_idx",
        ),
        migrations.AlterField(
            model_name="entitytag",
            name="applied_by",
            field=models.ForeignKey(
                help_text="User who applied this tag",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
