# Generated by ChatGPT on 2026-01-05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0004_campaign_recipient_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("prospect", "Prospect"),
                            ("client", "Client"),
                            ("contact", "Contact"),
                            ("account", "Account"),
                        ],
                        max_length=20,
                        help_text="Type of entity included in the segment",
                    ),
                ),
                ("entity_id", models.BigIntegerField(help_text="ID of the entity included in the segment")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        help_text="User who added this membership",
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="segment_memberships_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        help_text="Segment/list this membership belongs to",
                        on_delete=models.CASCADE,
                        related_name="memberships",
                        to="marketing.segment",
                    ),
                ),
            ],
            options={
                "db_table": "marketing_segment_memberships",
                "ordering": ["-added_at"],
                "unique_together": {("segment", "entity_type", "entity_id")},
            },
        ),
        migrations.AddIndex(
            model_name="segmentmembership",
            index=models.Index(fields=["segment", "entity_type"], name="marketing_segmem_seg_ent_idx"),
        ),
        migrations.AddIndex(
            model_name="segmentmembership",
            index=models.Index(fields=["entity_type", "entity_id"], name="marketing_segmem_ent_idx"),
        ),
    ]
