# Generated by Django 4.2.8 on 2025-12-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_organization_client_organization"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_cli_organiz_c54e76_idx",
            old_name="clients_cli_org_idx",
        ),
        migrations.RenameIndex(
            model_name="organization",
            new_name="clients_org_firm_id_16df07_idx",
            old_name="clients_org_firm_name_idx",
        ),
    ]
