# Generated by Django 4.2.8 on 2025-12-23 12:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                ("vendor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "bill_number",
                    models.CharField(
                        help_text="Vendor's bill/invoice number", max_length=50
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Our internal reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("disputed", "Disputed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount paid to vendor",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("bill_date", models.DateField(help_text="Date on vendor's bill")),
                ("due_date", models.DateField()),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="Date when bill was fully paid", null=True
                    ),
                ),
                (
                    "expense_category",
                    models.CharField(
                        help_text="e.g., Software, Travel, Office Supplies",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "line_items",
                    models.JSONField(
                        default=list,
                        help_text="List of line items: [{description, quantity, rate, amount}, ...]",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_bills",
                "ordering": ["-bill_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Client"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount received from client",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "payment_terms",
                    models.CharField(
                        default="Net 30",
                        help_text="e.g., Net 30, Due on Receipt",
                        max_length=50,
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when invoice was fully paid",
                        null=True,
                    ),
                ),
                (
                    "line_items",
                    models.JSONField(
                        default=list,
                        help_text="List of line items: [{description, quantity, rate, amount}, ...]",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes visible to client on invoice"
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Invoice ID if using Stripe billing",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The post-sale client being invoiced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finance_invoices",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("accounts_receivable", "Accounts Receivable"),
                            ("equipment", "Equipment"),
                            ("accounts_payable", "Accounts Payable"),
                            ("loans_payable", "Loans Payable"),
                            ("owners_equity", "Owner's Equity"),
                            ("retained_earnings", "Retained Earnings"),
                            ("consulting_revenue", "Consulting Revenue"),
                            ("other_income", "Other Income"),
                            ("salaries_expense", "Salaries Expense"),
                            ("software_expense", "Software Expense"),
                            ("travel_expense", "Travel Expense"),
                            ("office_expense", "Office Supplies"),
                            ("other_expense", "Other Expense"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                (
                    "transaction_group_id",
                    models.CharField(
                        help_text="UUID to group related debit/credit entries",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="finance.bill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="finance.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ledger Entries",
                "db_table": "finance_ledger_entries",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
