# Generated by Django 4.2.8 on 2025-12-23 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to specific project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to project if this is a project expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["account", "transaction_date"],
                name="finance_led_account_f3cabb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["transaction_group_id"], name="finance_led_transac_2de4fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client", "status"], name="finance_inv_client__c0cea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="finance_inv_invoice_dd3aad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="finance_inv_due_dat_58b34d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["vendor_name", "status"], name="finance_bil_vendor__c28923_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["reference_number"], name="finance_bil_referen_8a169e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["due_date"], name="finance_bil_due_dat_523ab2_idx"
            ),
        ),
    ]
