# Generated by Django 4.2.8 on 2025-12-23 12:41

from django.db import migrations, models
import django.db.models.deletion


def populate_finance_firms(apps, schema_editor):
    Firm = apps.get_model("firm", "Firm")
    Invoice = apps.get_model("finance", "Invoice")
    Bill = apps.get_model("finance", "Bill")
    LedgerEntry = apps.get_model("finance", "LedgerEntry")

    single_firm_id = None
    firm_count = Firm.objects.count()
    if firm_count == 1:
        single_firm_id = Firm.objects.values_list("id", flat=True).first()

    for invoice in Invoice.objects.filter(firm__isnull=True).select_related("client"):
        invoice.firm_id = invoice.client.firm_id
        invoice.save(update_fields=["firm"])

    for bill in Bill.objects.filter(firm__isnull=True).select_related("project"):
        if bill.project_id:
            bill.firm_id = bill.project.firm_id
            bill.save(update_fields=["firm"])
            continue
        if single_firm_id:
            bill.firm_id = single_firm_id
            bill.save(update_fields=["firm"])
            continue
        raise ValueError("Bill is missing firm assignment and no single firm exists.")

    for entry in LedgerEntry.objects.filter(firm__isnull=True).select_related("invoice", "bill"):
        if entry.invoice_id:
            entry.firm_id = entry.invoice.firm_id
            entry.save(update_fields=["firm"])
            continue
        if entry.bill_id:
            entry.firm_id = entry.bill.firm_id
            entry.save(update_fields=["firm"])
            continue
        if single_firm_id:
            entry.firm_id = single_firm_id
            entry.save(update_fields=["firm"])
            continue
        raise ValueError("Ledger entry is missing firm assignment and no single firm exists.")


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("firm", "0001_initial"),
        ("finance", "0002_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this invoice belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this bill belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this ledger entry belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="firm.firm",
            ),
        ),
        migrations.RunPython(populate_finance_firms, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invoice",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this invoice belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="firm.firm",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this bill belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="firm.firm",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this ledger entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="firm.firm",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bill",
            name="reference_number",
            field=models.CharField(
                help_text="Our internal reference number", max_length=50
            ),
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_client__c0cea9_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_invoice_dd3aad_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_due_dat_58b34d_idx",
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["firm", "client", "status"],
                name="finance_inv_firm_c_40e418_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["firm", "invoice_number"],
                name="finance_inv_firm_i_85c3a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["firm", "due_date"],
                name="finance_inv_firm_d_d5b1ed_idx",
            ),
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="finance_bil_vendor__c28923_idx",
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="finance_bil_referen_8a169e_idx",
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="finance_bil_due_dat_523ab2_idx",
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["firm", "vendor_name", "status"],
                name="finance_bil_firm_v_6f61f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["firm", "reference_number"],
                name="finance_bil_firm_r_4e8f5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["firm", "due_date"],
                name="finance_bil_firm_d_5b8c41_idx",
            ),
        ),
        migrations.RemoveIndex(
            model_name="ledgerentry",
            name="finance_led_account_f3cabb_idx",
        ),
        migrations.RemoveIndex(
            model_name="ledgerentry",
            name="finance_led_transac_2de4fe_idx",
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["firm", "account", "transaction_date"],
                name="finance_led_firm_a_6f1a0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["firm", "transaction_group_id"],
                name="finance_led_firm_t_3f2249_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("firm", "invoice_number")},
        ),
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together={("firm", "reference_number")},
        ),
    ]
