# Generated by Django for DOC-13.1 and DOC-13.2 - Billing Ledger

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firm', '0007_provisioninglog'),
        ('crm', '0001_initial'),
        ('finance', '0007_auto_payment_failures'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('invoice_issued', 'Invoice Issued'), ('payment_received', 'Payment Received'), ('retainer_deposit', 'Retainer Deposit'), ('retainer_applied', 'Retainer Applied'), ('credit_memo', 'Credit Memo'), ('adjustment', 'Adjustment'), ('write_off', 'Write-Off')], help_text='Type of billing event', max_length=20)),
                ('idempotency_key', models.CharField(help_text='Unique key for idempotent posting (required)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount (signed; typically positive per spec)', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('occurred_at', models.DateTimeField(help_text='Business time when the event occurred')),
                ('posted_at', models.DateTimeField(auto_now_add=True, help_text='System time when entry was posted (immutable)')),
                ('reference', models.CharField(blank=True, help_text='External reference (check number, processor ref, etc.)', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Bounded metadata (reason codes, processor details, etc.)')),
                ('correlation_id', models.CharField(blank=True, help_text='Correlation ID for request tracing', max_length=255)),
                ('account', models.ForeignKey(help_text='Account (Client) this entry belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='billing_ledger_entries', to='crm.client')),
                ('created_by_actor', models.ForeignKey(help_text='Actor who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, help_text='Engagement reference (nullable, Contract=Engagement per DOC-06.1)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_ledger_entries', to='crm.contract')),
                ('firm', models.ForeignKey(help_text='Firm this ledger entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='billing_ledger_entries', to='firm.firm')),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice reference (nullable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_ledger_entries', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Billing Ledger Entry',
                'verbose_name_plural': 'Billing Ledger Entries',
                'db_table': 'billing_ledger_entry',
                'ordering': ['-posted_at', '-occurred_at'],
                'unique_together': {('firm', 'entry_type', 'idempotency_key')},
            },
        ),
        migrations.CreateModel(
            name='BillingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated (must be positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When allocation was created')),
                ('correlation_id', models.CharField(blank=True, help_text='Correlation ID for request tracing', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Additional allocation metadata')),
                ('created_by_actor', models.ForeignKey(help_text='Actor who created this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_allocations', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(help_text='Firm this allocation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='billing_allocations', to='firm.firm')),
                ('from_entry', models.ForeignKey(help_text='Source ledger entry (payment, retainer deposit, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='allocations_from', to='finance.billingledgerentry')),
                ('to_entry', models.ForeignKey(help_text='Target ledger entry (typically invoice_issued)', on_delete=django.db.models.deletion.PROTECT, related_name='allocations_to', to='finance.billingledgerentry')),
            ],
            options={
                'verbose_name': 'Billing Allocation',
                'verbose_name_plural': 'Billing Allocations',
                'db_table': 'billing_allocation',
                'ordering': ['-created_at'],
                'unique_together': {('from_entry', 'to_entry')},
            },
        ),
        migrations.AddIndex(
            model_name='billingledgerentry',
            index=models.Index(fields=['firm', 'account', '-posted_at'], name='idx_billingledgerentry__firm_account_posted'),
        ),
        migrations.AddIndex(
            model_name='billingledgerentry',
            index=models.Index(fields=['firm', 'entry_type'], name='idx_billingledgerentry__firm_entry_type'),
        ),
        migrations.AddIndex(
            model_name='billingledgerentry',
            index=models.Index(fields=['firm', 'invoice'], name='idx_billingledgerentry__firm_invoice'),
        ),
        migrations.AddIndex(
            model_name='billingledgerentry',
            index=models.Index(fields=['firm', '-occurred_at'], name='idx_billingledgerentry__firm_occurred'),
        ),
        migrations.AddIndex(
            model_name='billingledgerentry',
            index=models.Index(fields=['idempotency_key'], name='idx_billingledgerentry__idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='billingallocation',
            index=models.Index(fields=['firm', 'from_entry'], name='idx_billingallocation__firm_from'),
        ),
        migrations.AddIndex(
            model_name='billingallocation',
            index=models.Index(fields=['firm', 'to_entry'], name='idx_billingallocation__firm_to'),
        ),
        migrations.AddIndex(
            model_name='billingallocation',
            index=models.Index(fields=['firm', '-created_at'], name='idx_billingallocation__firm_created'),
        ),
    ]
