# Generated by manual migration for SEC-1 idempotency keys

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_squarewebhookevent_sec1"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripewebhookevent",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Idempotency key for this webhook event",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="squarewebhookevent",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Idempotency key for this webhook event",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
