# Generated by Django 4.2.8 on 2025-12-24 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("clients", "0003_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to specific project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folders",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="client",
            field=models.ForeignKey(
                help_text="Denormalized for quick filtering (post-sale client)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this document belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.folder",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to specific project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="version",
            index=models.Index(
                fields=["firm", "document", "version_number"],
                name="documents_v_firm_id_c5616a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="version",
            index=models.Index(
                fields=["firm", "s3_bucket", "s3_key"],
                name="documents_v_firm_id_8f01f7_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="version",
            unique_together={
                ("firm", "document", "version_number"),
                ("firm", "s3_bucket", "s3_key"),
            },
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["firm", "client", "parent"],
                name="documents_f_firm_id_0deb78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["firm", "visibility"], name="documents_f_firm_id_e9c246_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("firm", "client", "parent", "name")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["firm", "client", "folder"],
                name="documents_d_firm_id_4fb8e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["firm", "visibility"], name="documents_d_firm_id_385a6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["firm", "s3_bucket", "s3_key"],
                name="documents_d_firm_id_04b8ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["firm", "-created_at"], name="documents_d_firm_id_51ade2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("firm", "s3_bucket", "s3_key")},
        ),
    ]
