# Generated by Django 4.2.8 on 2025-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firm", "0005_firm_kms_key_id"),
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="documents_d_firm_id_04b8ed_idx",
        ),
        migrations.RemoveIndex(
            model_name="version",
            name="documents_v_firm_id_8f01f7_idx",
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="version",
            unique_together={("firm", "document", "version_number")},
        ),
        migrations.AddField(
            model_name="document",
            name="s3_fingerprint",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="Deterministic fingerprint for uniqueness checks",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="s3_fingerprint",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="Deterministic fingerprint for version content",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="s3_bucket",
            field=models.TextField(help_text="Encrypted S3 bucket name"),
        ),
        migrations.AlterField(
            model_name="document",
            name="s3_key",
            field=models.TextField(help_text="Encrypted S3 object key (path in bucket, unique per firm)"),
        ),
        migrations.AlterField(
            model_name="version",
            name="s3_bucket",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="version",
            name="s3_key",
            field=models.TextField(help_text="Encrypted S3 object key for this version (unique per firm)"),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("firm", "s3_fingerprint")},
        ),
        migrations.AlterUniqueTogether(
            name="version",
            unique_together={("firm", "document", "version_number"), ("firm", "s3_fingerprint")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["firm", "s3_fingerprint"], name="documents_d_firm_id_fe9435_idx"),
        ),
        migrations.AddIndex(
            model_name="version",
            index=models.Index(fields=["firm", "s3_fingerprint"], name="documents_v_firm_id_dd0ba2_idx"),
        ),
    ]
