# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0003_remove_document_documents_d_firm_id_04b8ed_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="classification",
            field=models.CharField(
                choices=[
                    ("PUB", "Public"),
                    ("INT", "Internal"),
                    ("CONF", "Confidential"),
                    ("R-PII", "Restricted PII"),
                    ("HR", "Highly Restricted"),
                ],
                default="CONF",
                help_text="Data classification level for governance",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deprecated_at",
            field=models.DateTimeField(blank=True, help_text="When the document was deprecated", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="deprecated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deprecated the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_deprecated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deprecation_reason",
            field=models.TextField(blank=True, help_text="Reason for deprecating the document"),
        ),
        migrations.AddField(
            model_name="document",
            name="legal_hold",
            field=models.BooleanField(
                default=False, help_text="Whether document is under legal hold (prevents deletion)"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="legal_hold_applied_at",
            field=models.DateTimeField(blank=True, help_text="When legal hold was applied", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="legal_hold_applied_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who applied the legal hold",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_legal_holds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="legal_hold_reason",
            field=models.TextField(blank=True, help_text="Reason for legal hold (e.g., litigation, investigation)"),
        ),
        migrations.AddField(
            model_name="document",
            name="published_at",
            field=models.DateTimeField(blank=True, help_text="When the document was published", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_published",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="retention_period_years",
            field=models.IntegerField(
                blank=True, help_text="Number of years to retain document (null = permanent)", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="retention_policy",
            field=models.CharField(
                blank=True, help_text="Retention policy name (e.g., '7years', 'permanent', 'standard')", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="retention_start_date",
            field=models.DateField(
                blank=True, help_text="Date when retention period starts (usually creation date)", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="review_notes",
            field=models.TextField(blank=True, help_text="Reviewer notes/feedback"),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, help_text="When the document was reviewed/approved", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reviewed/approved the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="scheduled_deletion_date",
            field=models.DateField(
                blank=True, help_text="Date when document is scheduled for deletion (if applicable)", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Under Review"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("active", "Active"),
                    ("deprecated", "Deprecated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Document status (draft → review → approved → published)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="submitted_for_review_at",
            field=models.DateTimeField(blank=True, help_text="When the document was submitted for review", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="submitted_for_review_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the document for review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_submitted_for_review",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="checksum",
            field=models.CharField(
                blank=True, help_text="SHA-256 checksum of file content for integrity verification", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="virus_scan_completed_at",
            field=models.DateTimeField(blank=True, help_text="When the virus scan was completed", null=True),
        ),
        migrations.AddField(
            model_name="version",
            name="virus_scan_result_detail",
            field=models.TextField(
                blank=True, help_text="Additional scan result details (e.g., detection name if flagged)"
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="virus_scan_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Scan"),
                    ("clean", "Clean"),
                    ("flagged", "Flagged (Malware Detected)"),
                    ("skipped", "Scan Skipped"),
                ],
                default="pending",
                help_text="Malware scan status for this version",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExternalShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "share_token",
                    models.UUIDField(
                        db_index=True, editable=False, help_text="Unique token for accessing this share", unique=True
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("view", "View Only"), ("download", "Download"), ("comment", "View & Comment")],
                        default="view",
                        help_text="Type of access granted",
                        max_length=20,
                    ),
                ),
                (
                    "require_password",
                    models.BooleanField(default=False, help_text="Whether password is required to access"),
                ),
                (
                    "password_hash",
                    models.CharField(blank=True, help_text="Bcrypt hash of the password (if required)", max_length=128),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this share expires (null = no expiration)", null=True
                    ),
                ),
                (
                    "max_downloads",
                    models.IntegerField(
                        blank=True, help_text="Maximum number of downloads allowed (null = unlimited)", null=True
                    ),
                ),
                ("download_count", models.IntegerField(default=0, help_text="Current number of downloads")),
                ("revoked", models.BooleanField(default=False, help_text="Whether this share has been revoked")),
                ("revoked_at", models.DateTimeField(blank=True, help_text="When this share was revoked", null=True)),
                ("revoke_reason", models.TextField(blank=True, help_text="Reason for revocation")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this share",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document being shared externally",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_shares",
                        to="documents.document",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this share belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_shares",
                        to="firm.firm",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who revoked this share",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents_external_shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentLock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("locked_at", models.DateTimeField(auto_now_add=True, help_text="When the lock was acquired")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the lock expires (null = no auto-expiry)", null=True
                    ),
                ),
                ("lock_reason", models.TextField(blank=True, help_text="Optional reason for the lock")),
                ("override_at", models.DateTimeField(blank=True, help_text="When the lock was overridden", null=True)),
                (
                    "override_reason",
                    models.TextField(blank=True, help_text="Reason for the admin override (required for audit)"),
                ),
                (
                    "document",
                    models.OneToOneField(
                        help_text="The document this lock applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock",
                        to="documents.document",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this lock belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_locks",
                        to="firm.firm",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        help_text="User who holds the lock",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_locks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "override_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who overrode this lock (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_lock_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents_locks",
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("url_issued", "Signed URL Issued"),
                            ("download", "Download"),
                            ("upload", "Upload"),
                            ("view", "View"),
                            ("version_created", "Version Created"),
                            ("lock_acquired", "Lock Acquired"),
                            ("lock_released", "Lock Released"),
                            ("lock_overridden", "Lock Overridden"),
                        ],
                        help_text="Type of access action",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("staff", "Staff User"),
                            ("portal", "Portal User"),
                            ("system", "System/Background Job"),
                        ],
                        help_text="Type of actor (staff, portal, system)",
                        max_length=10,
                    ),
                ),
                (
                    "actor_portal_user_id",
                    models.IntegerField(blank=True, help_text="Portal user ID if actor is a portal user", null=True),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, help_text="Correlation ID for request tracing", max_length=64
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address of the request", null=True),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string (truncated for logging)")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (must not contain document content or PII)",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document accessed (null if deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_access_logs",
                        to="firm.firm",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific version accessed (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="documents.version",
                    ),
                ),
            ],
            options={
                "db_table": "documents_access_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SharePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allow_print", models.BooleanField(default=True, help_text="Allow printing the document")),
                ("allow_copy", models.BooleanField(default=True, help_text="Allow copying text from the document")),
                ("apply_watermark", models.BooleanField(default=False, help_text="Whether to apply a watermark")),
                ("watermark_text", models.CharField(blank=True, help_text="Watermark text to display", max_length=255)),
                (
                    "watermark_settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional watermark settings (opacity, position, etc.)"
                    ),
                ),
                (
                    "allowed_ip_addresses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed IP addresses/ranges (empty = no restriction)",
                    ),
                ),
                (
                    "notify_on_access",
                    models.BooleanField(default=False, help_text="Send notification when document is accessed"),
                ),
                (
                    "notification_emails",
                    models.JSONField(blank=True, default=list, help_text="Email addresses to notify on access"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_share",
                    models.OneToOneField(
                        help_text="The external share these permissions apply to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="documents.externalshare",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this permission belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_permissions",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "documents_share_permissions",
                "indexes": [models.Index(fields=["firm", "external_share"], name="doc_sha_fir_ext_idx")],
            },
        ),
        migrations.CreateModel(
            name="ShareAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("download", "Download"),
                            ("failed_password", "Failed Password"),
                            ("failed_expired", "Failed - Expired"),
                            ("failed_revoked", "Failed - Revoked"),
                            ("failed_limit", "Failed - Download Limit"),
                            ("failed_ip", "Failed - IP Restricted"),
                        ],
                        help_text="Type of access action",
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(help_text="Whether the access was successful")),
                (
                    "accessed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text="When the access occurred"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address of the request", null=True),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string")),
                ("referer", models.TextField(blank=True, help_text="HTTP referer")),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional access metadata")),
                (
                    "external_share",
                    models.ForeignKey(
                        help_text="The external share being accessed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="documents.externalshare",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this access belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_accesses",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "documents_share_accesses",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(fields=["firm", "external_share", "-accessed_at"], name="doc_sha_fir_ext_acc_idx"),
                    models.Index(fields=["firm", "action", "-accessed_at"], name="doc_sha_fir_act_acc_idx"),
                    models.Index(fields=["ip_address", "-accessed_at"], name="doc_sha_ip_acc_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="externalshare",
            index=models.Index(fields=["firm", "document"], name="doc_ext_fir_doc_idx"),
        ),
        migrations.AddIndex(
            model_name="externalshare",
            index=models.Index(fields=["firm", "created_by"], name="doc_ext_fir_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="externalshare",
            index=models.Index(fields=["expires_at"], name="doc_ext_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="externalshare",
            index=models.Index(fields=["revoked"], name="doc_ext_rev_idx"),
        ),
        migrations.AddIndex(
            model_name="documentlock",
            index=models.Index(fields=["firm", "document"], name="documents_fir_doc_idx"),
        ),
        migrations.AddIndex(
            model_name="documentlock",
            index=models.Index(fields=["firm", "locked_by"], name="documents_fir_loc_idx"),
        ),
        migrations.AddIndex(
            model_name="documentlock",
            index=models.Index(fields=["firm", "expires_at"], name="documents_fir_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(fields=["firm", "document", "-timestamp"], name="doc_acc_fir_doc_tim_idx"),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(fields=["firm", "actor_user", "-timestamp"], name="doc_acc_fir_act_usr_idx"),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(fields=["firm", "action", "-timestamp"], name="doc_acc_fir_act_tim_idx"),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(fields=["correlation_id"], name="doc_acc_cor_idx"),
        ),
    ]
