# Generated by Django 4.2.8 on 2025-12-24 02:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        help_text="Unique identifier per firm (e.g., barcode, serial number)",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("computer", "Computer Equipment"),
                            ("software", "Software License"),
                            ("furniture", "Furniture"),
                            ("vehicle", "Vehicle"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("in_repair", "In Repair"),
                            ("retired", "Retired"),
                            ("lost", "Lost/Stolen"),
                            ("disposed", "Disposed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original purchase price",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("purchase_date", models.DateField()),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Where was this purchased?",
                        max_length=255,
                    ),
                ),
                (
                    "useful_life_years",
                    models.IntegerField(
                        default=3,
                        help_text="Expected useful life for depreciation calculation",
                    ),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected value at end of useful life",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location (e.g., office, warehouse)",
                        max_length=255,
                    ),
                ),
                ("warranty_expiration", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user currently using this asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "assets_assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("repair", "Repair"),
                            ("preventive", "Preventive Maintenance"),
                            ("upgrade", "Upgrade"),
                            ("inspection", "Inspection"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What maintenance was performed?"),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "performed_by",
                    models.CharField(
                        help_text="Technician name or company", max_length=255
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, help_text="Service provider company", max_length=255
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost of maintenance/repair",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_maintenance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this maintenance log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "assets_maintenance_logs",
                "ordering": ["-scheduled_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "asset", "status"],
                        name="assets_main_firm_id_63cf61_idx",
                    ),
                    models.Index(
                        fields=["firm", "scheduled_date"],
                        name="assets_main_firm_id_4f8979_idx",
                    ),
                    models.Index(
                        fields=["firm", "status"], name="assets_main_firm_id_4db075_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["firm", "asset_tag"], name="assets_asse_firm_id_488d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["firm", "category", "status"],
                name="assets_asse_firm_id_825c0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["firm", "assigned_to"], name="assets_asse_firm_id_eca138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["firm", "status"], name="assets_asse_firm_id_be21b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("firm", "asset_tag")},
        ),
    ]
