# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0008_contact_engagementline_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quote_number", models.CharField(help_text="Human-readable quote number", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("valid_until", models.DateField(blank=True, help_text="Quote expiration date", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="quotes", to="clients.client"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pricing_quote",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Human-readable name for this ruleset", max_length=255)),
                ("code", models.CharField(help_text="Stable code identifier for this ruleset", max_length=100)),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Monotonic version number (increments on each publish)"),
                ),
                (
                    "schema_version",
                    models.CharField(default="1.0.0", help_text="Pricing JSON schema version", max_length=20),
                ),
                ("rules_json", models.JSONField(default=dict, help_text="The pricing rules in JSON format")),
                (
                    "checksum",
                    models.CharField(blank=True, help_text="SHA-256 checksum of normalized rules JSON", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("deprecated", "Deprecated")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, help_text="When this ruleset was published", null=True),
                ),
                (
                    "deprecated_at",
                    models.DateTimeField(blank=True, help_text="When this ruleset was deprecated", null=True),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="USD", help_text="Default currency for this ruleset (ISO 4217)", max_length=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rulesets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this ruleset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rulesets",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_ruleset",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="QuoteVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.IntegerField(default=1, help_text="Version number within the quote")),
                (
                    "ruleset_checksum",
                    models.CharField(
                        help_text="Checksum of ruleset at time of evaluation (for reproducibility)", max_length=64
                    ),
                ),
                (
                    "context_snapshot",
                    models.JSONField(default=dict, help_text="Snapshot of evaluation context (bounded, no HR data)"),
                ),
                ("line_items", models.JSONField(default=list, help_text="Computed line items")),
                (
                    "totals",
                    models.JSONField(default=dict, help_text="Computed totals (subtotal, discounts, taxes, total)"),
                ),
                ("assumptions", models.JSONField(default=list, help_text="List of assumption statements")),
                ("warnings", models.JSONField(default=list, help_text="Validation or policy warnings")),
                ("evaluation_trace", models.JSONField(default=dict, help_text="Complete evaluation trace for audit")),
                (
                    "outputs_checksum",
                    models.CharField(blank=True, help_text="Checksum of evaluation outputs", max_length=64),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("accepted", "Accepted"),
                            ("superseded", "Superseded"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, help_text="Correlation ID from evaluation request", max_length=64),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_quote_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="quote_versions", to="firm.firm"
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_quote_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="pricing.quote"
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        help_text="The ruleset used for evaluation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_versions",
                        to="pricing.ruleset",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_quote_version",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.IntegerField(help_text="Line number within the quote version")),
                ("product_code", models.CharField(help_text="Product code from ruleset", max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "billing_model",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Fee"),
                            ("recurring", "Recurring"),
                            ("usage", "Usage-Based"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "billing_unit",
                    models.CharField(
                        blank=True, help_text="Billing unit (month, quarter, project, hour, etc.)", max_length=50
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("tax_category", models.CharField(blank=True, max_length=50)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="quote_line_items", to="firm.firm"
                    ),
                ),
                (
                    "quote_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_item_records",
                        to="pricing.quoteversion",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_quote_line_item",
                "ordering": ["line_number"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Current active version of this quote",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pricing.quoteversion",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="firm",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quotes", to="firm.firm"),
        ),
        migrations.AddIndex(
            model_name="ruleset",
            index=models.Index(fields=["firm", "code", "-version"], name="pricing_fir_cod_ver_idx"),
        ),
        migrations.AddIndex(
            model_name="ruleset",
            index=models.Index(fields=["firm", "status"], name="pricing_rul_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="ruleset",
            index=models.Index(fields=["checksum"], name="pricing_che_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ruleset",
            unique_together={("firm", "code", "version")},
        ),
        migrations.AddIndex(
            model_name="quoteversion",
            index=models.Index(fields=["firm", "quote", "-version_number"], name="pricing_fir_quo_ver_idx"),
        ),
        migrations.AddIndex(
            model_name="quoteversion",
            index=models.Index(fields=["firm", "status"], name="pricing_ver_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="quoteversion",
            index=models.Index(fields=["firm", "ruleset"], name="pricing_fir_rul_idx"),
        ),
        migrations.AddIndex(
            model_name="quoteversion",
            index=models.Index(fields=["correlation_id"], name="pricing_cor_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="quoteversion",
            unique_together={("quote", "version_number")},
        ),
        migrations.AddIndex(
            model_name="quotelineitem",
            index=models.Index(fields=["firm", "quote_version", "line_number"], name="pricing_fir_quo_lin_idx"),
        ),
        migrations.AddIndex(
            model_name="quotelineitem",
            index=models.Index(fields=["firm", "product_code"], name="pricing_fir_pro_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="quotelineitem",
            unique_together={("quote_version", "line_number")},
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["firm", "client", "-created_at"], name="pricing_fir_cli_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["firm", "status"], name="pricing_quo_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["firm", "quote_number"], name="pricing_fir_quo_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="quote",
            unique_together={("firm", "quote_number")},
        ),
    ]
