# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firm", "0012_user_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provisioninglog",
            name="firm",
        ),
        migrations.RemoveField(
            model_name="provisioninglog",
            name="initiated_by",
        ),
        migrations.RenameIndex(
            model_name="firm",
            new_name="firm_sta_idx",
            old_name="firm_firm_status_4da2cd_idx",
        ),
        migrations.RenameIndex(
            model_name="firm",
            new_name="firm_slu_idx",
            old_name="firm_firm_slug_0a631f_idx",
        ),
        migrations.RenameIndex(
            model_name="firm",
            new_name="firm_sub_idx",
            old_name="firm_firm_subscri_450f9a_idx",
        ),
        migrations.RenameIndex(
            model_name="firmmembership",
            new_name="firm_fir_is__idx",
            old_name="firm_member_firm_id_927315_idx",
        ),
        migrations.RenameIndex(
            model_name="firmmembership",
            new_name="firm_use_is__idx",
            old_name="firm_member_user_id_40e1bb_idx",
        ),
        migrations.RenameIndex(
            model_name="firmmembership",
            new_name="firm_rol_idx",
            old_name="firm_member_role_b4e9ab_idx",
        ),
        migrations.RenameIndex(
            model_name="firmoffboardingrecord",
            new_name="firm_fir_exp_idx",
            old_name="firm_offbo_firm_id_31c9ee_idx",
        ),
        migrations.RenameIndex(
            model_name="firmoffboardingrecord",
            new_name="firm_sta_exp_idx",
            old_name="firm_offbo_status_3a9f79_idx",
        ),
        migrations.DeleteModel(
            name="ProvisioningLog",
        ),
    ]
