# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SnippetFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Folder name", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Folder description")),
                (
                    "is_shared",
                    models.BooleanField(default=False, help_text="If True, folder is visible to all team members"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this folder",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snippet_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this folder belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippet_folders",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "snippet_folders",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Snippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="If True, snippet is available to all team members; if False, only creator can use it",
                    ),
                ),
                (
                    "shared_with_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of role names this snippet is shared with (empty = all roles if is_shared=True)",
                    ),
                ),
                (
                    "shortcut",
                    models.CharField(
                        help_text='Shortcut trigger (e.g., "meeting", "followup"). Type # + shortcut to insert',
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(help_text="Descriptive name for this snippet", max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="Snippet content with optional variables: {{contact_name}}, {{company_name}}, {{my_name}}, etc."
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("all", "All Contexts"),
                            ("email", "Email Only"),
                            ("ticket", "Tickets Only"),
                            ("message", "Messages Only"),
                            ("note", "Notes Only"),
                        ],
                        default="all",
                        help_text="Where this snippet can be used",
                        max_length=20,
                    ),
                ),
                ("usage_count", models.IntegerField(default=0, help_text="Number of times this snippet has been used")),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, help_text="When this snippet was last used", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this snippet is active and available for use"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this snippet",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_snippets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this snippet belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to="firm.firm",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Folder this snippet belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snippets",
                        to="snippets.snippetfolder",
                    ),
                ),
            ],
            options={
                "db_table": "snippets",
                "ordering": ["-usage_count", "shortcut"],
            },
        ),
        migrations.CreateModel(
            name="SnippetUsageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "context",
                    models.CharField(
                        help_text="Where the snippet was used (email, ticket, message, note)", max_length=20
                    ),
                ),
                (
                    "context_object_type",
                    models.CharField(
                        blank=True, help_text='Type of object (e.g., "ticket", "email", "message")', max_length=50
                    ),
                ),
                (
                    "context_object_id",
                    models.CharField(blank=True, help_text="ID of the object where snippet was used", max_length=100),
                ),
                (
                    "variables_used",
                    models.JSONField(default=dict, help_text="Variables that were replaced in this usage"),
                ),
                (
                    "rendered_length",
                    models.IntegerField(default=0, help_text="Length of rendered snippet (characters)"),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snippet",
                    models.ForeignKey(
                        help_text="Snippet that was used",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="snippets.snippet",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        help_text="User who used the snippet",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snippet_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "snippet_usage_logs",
                "ordering": ["-used_at"],
                "indexes": [
                    models.Index(fields=["snippet", "-used_at"], name="snippets_sni_use_idx"),
                    models.Index(fields=["used_by", "-used_at"], name="snippets_use_use_idx"),
                    models.Index(fields=["context", "-used_at"], name="snippets_con_use_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="snippetfolder",
            index=models.Index(fields=["firm", "created_by"], name="snippets_folder_fir_cre_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="snippetfolder",
            unique_together={("firm", "name", "created_by")},
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(fields=["firm", "shortcut"], name="snippets_fir_sho_idx"),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(fields=["firm", "is_shared"], name="snippets_fir_is__idx"),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(fields=["firm", "created_by"], name="snippets_snippet_fir_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(fields=["is_active"], name="snippets_is__idx"),
        ),
        migrations.AlterUniqueTogether(
            name="snippet",
            unique_together={("firm", "shortcut", "created_by")},
        ),
    ]
