# Generated by Django 4.2.8 on 2025-12-24 02:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Firm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Firm name (must be unique across platform)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for subdomain (e.g., 'acme-consulting')",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                message="Slug must contain only lowercase letters, numbers, and hyphens",
                                regex="^[a-z0-9-]+$",
                            ),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial Period"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When trial period ends (null if not on trial)",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/New_York",
                        help_text="Firm's default timezone",
                        max_length=50,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Default currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=5, help_text="Maximum number of firm users allowed"
                    ),
                ),
                (
                    "max_clients",
                    models.IntegerField(
                        default=25, help_text="Maximum number of active clients allowed"
                    ),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(
                        default=10, help_text="Maximum storage in gigabytes"
                    ),
                ),
                (
                    "current_users_count",
                    models.IntegerField(
                        default=0, help_text="Current number of active users"
                    ),
                ),
                (
                    "current_clients_count",
                    models.IntegerField(
                        default=0, help_text="Current number of active clients"
                    ),
                ),
                (
                    "current_storage_gb",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current storage usage in GB",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal platform notes (not visible to firm)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this firm",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_firms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "firm_firm",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FirmMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Firm Owner"),
                            ("admin", "Firm Admin"),
                            ("staff", "Staff Member"),
                            ("contractor", "Contractor"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False, help_text="Can invite/remove users"
                    ),
                ),
                (
                    "can_manage_clients",
                    models.BooleanField(
                        default=False, help_text="Can create/delete clients"
                    ),
                ),
                (
                    "can_manage_billing",
                    models.BooleanField(
                        default=False, help_text="Can view/modify billing"
                    ),
                ),
                (
                    "can_manage_settings",
                    models.BooleanField(
                        default=False, help_text="Can modify firm settings"
                    ),
                ),
                (
                    "can_view_reports",
                    models.BooleanField(
                        default=False, help_text="Can access analytics/reports"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this membership is currently active",
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_active_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time user was active in this firm",
                        null=True,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="firm.firm",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who invited this member",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_firm_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "firm_membership",
                "ordering": ["-invited_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "is_active"],
                        name="firm_member_firm_id_927315_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="firm_member_user_id_40e1bb_idx",
                    ),
                    models.Index(fields=["role"], name="firm_member_role_b4e9ab_idx"),
                ],
                "unique_together": {("firm", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="firm",
            index=models.Index(fields=["status"], name="firm_firm_status_4da2cd_idx"),
        ),
        migrations.AddIndex(
            model_name="firm",
            index=models.Index(fields=["slug"], name="firm_firm_slug_0a631f_idx"),
        ),
        migrations.AddIndex(
            model_name="firm",
            index=models.Index(
                fields=["subscription_tier"], name="firm_firm_subscri_450f9a_idx"
            ),
        ),
    ]
