# Generated by Django 4.2.8 on 2025-12-25 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Time entry approved for billing (default: False per Tier 4)"
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="approved_at",
            field=models.DateTimeField(blank=True, help_text="When time entry was approved for billing", null=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff/Admin who approved this time entry for billing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_time_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
