# Generated by Django 4.2.8 on 2025-12-23 12:41

from django.db import migrations, models
import django.db.models.deletion


def populate_task_firm(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Task = apps.get_model("projects", "Task")
    TimeEntry = apps.get_model("projects", "TimeEntry")

    project_firms = Project.objects.values_list("id", "firm_id")
    project_firm_map = {project_id: firm_id for project_id, firm_id in project_firms}

    tasks = Task.objects.filter(firm__isnull=True)
    for task in tasks:
        task.firm_id = project_firm_map.get(task.project_id)
        task.save(update_fields=["firm"])

    time_entries = TimeEntry.objects.filter(firm__isnull=True)
    for entry in time_entries:
        entry.firm_id = project_firm_map.get(entry.project_id)
        entry.save(update_fields=["firm"])


class Migration(migrations.Migration):

    dependencies = [
        ("firm", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this task belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this time entry belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="firm.firm",
            ),
        ),
        migrations.RunPython(populate_task_firm, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="task",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this task belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="firm.firm",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this time entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="firm.firm",
            ),
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="projects_ta_project_8bbd35_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="projects_ta_assigne_5ea120_idx",
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["firm", "project", "status"],
                name="projects_t_firm_p_4b1c6c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["firm", "assigned_to"],
                name="projects_t_firm_a_20563a_idx",
            ),
        ),
        migrations.RemoveIndex(
            model_name="timeentry",
            name="projects_ti_project_58d8f8_idx",
        ),
        migrations.RemoveIndex(
            model_name="timeentry",
            name="projects_ti_invoice_e209c9_idx",
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["firm", "project", "user", "date"],
                name="projects_t_firm_p_4ef2f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["firm", "invoiced"],
                name="projects_t_firm_i_0b14f3_idx",
            ),
        ),
    ]
