# Generated by Django 4.2.17 on 2026-01-01 04:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_chargeback_paymentfailure_stripewebhookevent_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0005_add_gantt_chart_timeline_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel", "Travel"),
                            ("meals", "Meals & Entertainment"),
                            ("supplies", "Office Supplies"),
                            ("software", "Software & Tools"),
                            ("subcontractor", "Subcontractor"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Description of the expense")),
                ("date", models.DateField(help_text="Date expense was incurred")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expense amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "is_billable",
                    models.BooleanField(default=True, help_text="Whether this expense should be billed to the client"),
                ),
                (
                    "markup_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Markup percentage for billable expenses (e.g., 10.00 for 10%)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "billable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount to bill to client (amount + markup)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("invoiced", "Invoiced"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, help_text="When expense was approved", null=True)),
                ("rejected_at", models.DateTimeField(blank=True, help_text="When expense was rejected", null=True)),
                ("rejection_reason", models.TextField(blank=True, help_text="Reason for rejection (if rejected)")),
                (
                    "invoiced",
                    models.BooleanField(default=False, help_text="Has this expense been included in an invoice?"),
                ),
                ("receipt_url", models.URLField(blank=True, help_text="URL to receipt document in S3")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Expenses",
                "db_table": "projects_expenses",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "template_name",
                    models.CharField(
                        help_text="Name of the template (e.g., 'Standard Tax Return', 'Audit Engagement')",
                        max_length=255,
                    ),
                ),
                ("template_code", models.CharField(help_text="Template code/identifier", max_length=50)),
                ("description", models.TextField(blank=True, help_text="Template description and usage notes")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Template category for organization (e.g., 'Tax', 'Audit', 'Consulting')",
                        max_length=100,
                    ),
                ),
                (
                    "default_billing_type",
                    models.CharField(
                        choices=[
                            ("fixed_price", "Fixed Price"),
                            ("time_and_materials", "Time & Materials"),
                            ("retainer", "Retainer"),
                            ("non_billable", "Non-Billable"),
                        ],
                        default="time_and_materials",
                        max_length=20,
                    ),
                ),
                (
                    "default_duration_days",
                    models.IntegerField(blank=True, help_text="Default project duration in days", null=True),
                ),
                (
                    "default_hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default hourly rate for projects created from this template",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "template_milestones",
                    models.JSONField(
                        default=list, help_text="Default milestones: [{name, description, days_from_start}, ...]"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this template is available for use"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects_templates",
                "ordering": ["category", "template_name"],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "default_status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("review", "In Review"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("position", models.IntegerField(default=0, help_text="Order in template (lower = higher priority)")),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "days_from_project_start",
                    models.IntegerField(blank=True, help_text="Due date offset from project start (days)", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects_task_templates",
                "ordering": ["project_template", "position"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="resourcecapacity",
            name="projects_resourcecapacity_resource_date_unique",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="projects_task_kanban_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="projects_task_assigned_idx",
        ),
        migrations.RemoveIndex(
            model_name="timeentry",
            name="projects_time_user_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="projects_tsk_pro_sta_idx",
            old_name="projects_ta_project_8bbd35_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="projects_ass_idx",
            old_name="projects_ta_assigne_5ea120_idx",
        ),
        migrations.RenameIndex(
            model_name="timeentry",
            new_name="projects_pro_use_dat_idx",
            old_name="projects_ti_project_58d8f8_idx",
        ),
        migrations.RenameIndex(
            model_name="timeentry",
            new_name="projects_inv_idx",
            old_name="projects_ti_invoice_e209c9_idx",
        ),
        migrations.RenameIndex(
            model_name="timeentry",
            new_name="projects_ti_project_32f043_idx",
            old_name="projects_time_bill_idx",
        ),
        migrations.AddField(
            model_name="project",
            name="acceptance_date",
            field=models.DateField(blank=True, help_text="Date when client accepted the project", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="acceptance_notes",
            field=models.TextField(blank=True, help_text="Notes or feedback from client acceptance"),
        ),
        migrations.AddField(
            model_name="project",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User (client portal user or staff) who marked the project as accepted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_accepted",
            field=models.BooleanField(
                default=False, help_text="Whether the client has accepted the project deliverables"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="last_billed_date",
            field=models.DateField(blank=True, help_text="Date of last invoice for this project", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="milestones",
            field=models.JSONField(
                default=list,
                help_text="List of project milestones: [{name, description, due_date, completed, completed_at}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="wip_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Unbilled amount accumulated (Work in Progress)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="wip_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Unbilled hours accumulated (Work in Progress)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="wip_last_calculated",
            field=models.DateTimeField(blank=True, help_text="When WIP was last calculated", null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks that must be completed before this task can start",
                related_name="blocking_tasks",
                to="projects.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="instantiation_id",
            field=models.IntegerField(blank=True, help_text="ID of TemplateInstantiation batch", null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.JSONField(blank=True, default=list, help_text="Tags/labels for this task"),
        ),
        migrations.AddField(
            model_name="task",
            name="template_id",
            field=models.IntegerField(
                blank=True, help_text="ID of DeliveryTemplate this task was created from", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="template_node_id",
            field=models.CharField(blank=True, help_text="Node ID within template", max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="template_version",
            field=models.IntegerField(blank=True, help_text="Version of template at instantiation", null=True),
        ),
        migrations.AlterUniqueTogether(
            name="resourcecapacity",
            unique_together={("resource", "date")},
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["project", "-date"], name="projects_ti_project_2974ea_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["user", "-date"], name="projects_ti_user_id_773ce8_idx"),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="depends_on_templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Template tasks that must be completed first",
                related_name="blocking_templates",
                to="projects.tasktemplate",
            ),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="project_template",
            field=models.ForeignKey(
                help_text="The project template this task belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_templates",
                to="projects.projecttemplate",
            ),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_project_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this template belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_templates",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="The invoice that includes this expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="project",
            field=models.ForeignKey(
                help_text="Project this expense belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who rejected this expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="submitted_by",
            field=models.ForeignKey(
                help_text="User who submitted this expense",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(fields=["project_template", "position"], name="projects_pro_pos_idx"),
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(fields=["firm", "is_active"], name="projects_fir_is__idx"),
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(fields=["firm", "category"], name="projects_fir_cat_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="projecttemplate",
            unique_together={("firm", "template_code")},
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["project", "status"], name="projects_exp_pro_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["submitted_by", "status"], name="projects_sub_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["date"], name="projects_dat_idx"),
        ),
    ]
