# Generated by Django 4.2.8 on 2025-12-24 02:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
        ("firm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email Campaign"),
                            ("webinar", "Webinar"),
                            ("content", "Content Marketing"),
                            ("event", "Event/Conference"),
                            ("social", "Social Media"),
                            ("partnership", "Partnership"),
                            ("renewal", "Renewal Campaign"),
                            ("annual_review", "Annual Review"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "target_leads",
                    models.IntegerField(
                        default=0, help_text="Target number of new leads"
                    ),
                ),
                (
                    "leads_generated",
                    models.IntegerField(
                        default=0,
                        help_text="Auto-calculated from Lead.campaign foreign key",
                    ),
                ),
                (
                    "opportunities_created",
                    models.IntegerField(
                        default=0,
                        help_text="Number of Prospects created from campaign leads",
                    ),
                ),
                (
                    "clients_contacted",
                    models.IntegerField(
                        default=0, help_text="Number of existing clients contacted"
                    ),
                ),
                (
                    "renewal_proposals_sent",
                    models.IntegerField(
                        default=0,
                        help_text="Number of renewal/upsell proposals generated",
                    ),
                ),
                (
                    "renewals_won",
                    models.IntegerField(
                        default=0, help_text="Number of successful renewals/upsells"
                    ),
                ),
                (
                    "revenue_generated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Revenue from won deals (new + renewal) attributed to this campaign",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this campaign belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="firm.firm",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "targeted_clients",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Existing clients targeted by this campaign (renewals, upsells, etc.)",
                        related_name="targeted_campaigns",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "crm_campaigns",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("contact_title", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website Form"),
                            ("referral", "Referral"),
                            ("campaign", "Marketing Campaign"),
                            ("cold_outreach", "Cold Outreach"),
                            ("event", "Event/Conference"),
                            ("partnership", "Partnership"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New Lead"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified - Moving to Sales"),
                            ("converted", "Converted to Prospect"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "lead_score",
                    models.IntegerField(
                        default=0, help_text="Automated or manual lead scoring (0-100)"
                    ),
                ),
                ("captured_date", models.DateField(auto_now_add=True)),
                ("first_contacted", models.DateField(blank=True, null=True)),
                ("qualified_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="Sales rep assigned to this lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Marketing campaign that generated this lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="crm.campaign",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this lead belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "crm_leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("employee_count", models.IntegerField(blank=True, null=True)),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated annual revenue",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("primary_contact_name", models.CharField(max_length=255)),
                ("primary_contact_email", models.EmailField(max_length=254)),
                ("primary_contact_phone", models.CharField(blank=True, max_length=50)),
                ("primary_contact_title", models.CharField(blank=True, max_length=100)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="USA", max_length=100)),
                (
                    "pipeline_stage",
                    models.CharField(
                        choices=[
                            ("discovery", "Discovery"),
                            ("needs_analysis", "Needs Analysis"),
                            ("proposal", "Proposal Sent"),
                            ("negotiation", "Negotiation"),
                            ("won", "Won - Converting to Client"),
                            ("lost", "Lost"),
                        ],
                        default="discovery",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        default=50, help_text="Win probability percentage (0-100)"
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated deal value",
                        max_digits=12,
                    ),
                ),
                (
                    "close_date_estimate",
                    models.DateField(help_text="Expected close date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("won_date", models.DateField(blank=True, null=True)),
                ("lost_date", models.DateField(blank=True, null=True)),
                ("lost_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="Account executive assigned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_prospects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this prospect belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prospects",
                        to="firm.firm",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original lead that created this prospect",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "db_table": "crm_prospects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            ("prospective_client", "Prospective Client - New Business"),
                            ("update_client", "Update Client - Expansion/Upsell"),
                            ("renewal_client", "Renewal Client - Contract Renewal"),
                        ],
                        default="prospective_client",
                        help_text="Type of proposal: new business, expansion, or renewal",
                        max_length=20,
                    ),
                ),
                ("proposal_number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Scope of work, deliverables, timeline"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("valid_until", models.DateField(help_text="Proposal expiration date")),
                ("estimated_start_date", models.DateField(blank=True, null=True)),
                ("estimated_end_date", models.DateField(blank=True, null=True)),
                (
                    "converted_to_engagement",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this proposal has been converted to engagement/contract",
                    ),
                ),
                (
                    "auto_create_project",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-create initial project when accepted",
                    ),
                ),
                (
                    "enable_portal_on_acceptance",
                    models.BooleanField(
                        default=True,
                        help_text="Enable client portal when proposal accepted (for prospective_client only)",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="For update_client or renewal_client proposals",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this proposal belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="firm.firm",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        help_text="For prospective_client proposals (new business)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="crm.prospect",
                    ),
                ),
            ],
            options={
                "db_table": "crm_proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        help_text="Statement of work, deliverables, terms"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                            ("on_hold", "On Hold"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("net_15", "Net 15"),
                            ("net_30", "Net 30"),
                            ("net_45", "Net 45"),
                            ("net_60", "Net 60"),
                            ("due_on_receipt", "Due on Receipt"),
                            ("milestone", "Milestone-based"),
                        ],
                        default="net_30",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("signed_date", models.DateField(blank=True, null=True)),
                (
                    "contract_file_url",
                    models.URLField(
                        blank=True, help_text="Link to signed contract PDF in S3"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The post-sale client this contract is with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="clients.client",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this contract belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="firm.firm",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        help_text="The proposal that led to this contract (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="crm.proposal",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        help_text="The consultant who signed this contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crm_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["firm", "pipeline_stage"], name="crm_prospec_firm_id_0d42e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["firm", "-created_at"], name="crm_prospec_firm_id_ed1e1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["firm", "assigned_to"], name="crm_prospec_firm_id_19f0a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["firm", "close_date_estimate"],
                name="crm_prospec_firm_id_e6e7fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["firm", "proposal_type", "status"],
                name="crm_proposa_firm_id_11b5d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["firm", "-created_at"], name="crm_proposa_firm_id_5aa73b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["firm", "prospect", "status"],
                name="crm_proposa_firm_id_1349de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["firm", "client", "status"],
                name="crm_proposa_firm_id_164420_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["firm", "proposal_number"],
                name="crm_proposa_firm_id_1be67e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="proposal",
            unique_together={("firm", "proposal_number")},
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["firm", "status"], name="crm_leads_firm_id_cec87a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["firm", "-created_at"], name="crm_leads_firm_id_9c691a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["firm", "assigned_to"], name="crm_leads_firm_id_562e34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["campaign"], name="crm_leads_campaig_c0672e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["firm", "status"], name="crm_contrac_firm_id_0ef700_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["firm", "client", "status"],
                name="crm_contrac_firm_id_64af3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["firm", "contract_number"],
                name="crm_contrac_firm_id_acbc7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["firm", "start_date", "end_date"],
                name="crm_contrac_firm_id_ff8c36_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("firm", "contract_number")},
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["firm", "status"], name="crm_campaig_firm_id_6a9326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["firm", "-start_date"], name="crm_campaig_firm_id_8430a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["firm", "type"], name="crm_campaig_firm_id_02690c_idx"
            ),
        ),
    ]
