# Generated by Django 4.2.8 on 2025-12-24 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0001_initial"),
        ("clients", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Only"),
                            ("client", "Visible to Client"),
                        ],
                        default="internal",
                        help_text="Can clients see this document in the portal?",
                        max_length=20,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="MIME type (e.g., application/pdf, image/png)",
                        max_length=50,
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(help_text="File size in bytes"),
                ),
                (
                    "s3_key",
                    models.CharField(
                        help_text="S3 object key (path in bucket, unique per firm)",
                        max_length=500,
                    ),
                ),
                (
                    "s3_bucket",
                    models.CharField(help_text="S3 bucket name", max_length=255),
                ),
                (
                    "current_version",
                    models.IntegerField(default=1, help_text="Current version number"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "documents_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "change_summary",
                    models.TextField(
                        blank=True, help_text="What changed in this version?"
                    ),
                ),
                ("file_type", models.CharField(max_length=50)),
                ("file_size_bytes", models.BigIntegerField()),
                (
                    "s3_key",
                    models.CharField(
                        help_text="S3 object key for this version (unique per firm)",
                        max_length=500,
                    ),
                ),
                ("s3_bucket", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this version belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to="firm.firm",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Only"),
                            ("client", "Visible to Client"),
                        ],
                        default="internal",
                        help_text="Can clients see this folder in the portal?",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The post-sale client who owns this folder",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this folder belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="firm.firm",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent folder (null = root folder)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="documents.folder",
                    ),
                ),
            ],
            options={
                "db_table": "documents_folders",
                "ordering": ["name"],
            },
        ),
    ]
