# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communications", "__first__"),
        ("clients", "0008_contact_engagementline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        ("projects", "0006_expense_projecttemplate_tasktemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="SLA policy name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Policy description")),
                (
                    "priority",
                    models.CharField(
                        choices=[("critical", "Critical"), ("high", "High"), ("normal", "Normal"), ("low", "Low")],
                        help_text="Ticket priority this SLA applies to",
                        max_length=20,
                    ),
                ),
                (
                    "first_response_minutes",
                    models.IntegerField(
                        help_text="Target time for first response (minutes)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "resolution_minutes",
                    models.IntegerField(
                        help_text="Target time for resolution (minutes)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "business_hours_only",
                    models.BooleanField(default=True, help_text="Count only business hours (Mon-Fri 9-5) toward SLA"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Is this policy active?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sla_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this SLA policy belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_policies",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SLA Policies",
                "db_table": "support_sla_policies",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Survey name (internal)", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Survey description")),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("nps", "Net Promoter Score (NPS)"),
                            ("csat", "Customer Satisfaction (CSAT)"),
                            ("ces", "Customer Effort Score (CES)"),
                            ("custom", "Custom Survey"),
                        ],
                        default="csat",
                        help_text="Type of survey",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Survey status",
                        max_length=20,
                    ),
                ),
                ("introduction_text", models.TextField(blank=True, help_text="Introduction text shown to respondents")),
                (
                    "questions",
                    models.JSONField(default=list, help_text="List of survey questions with type and options"),
                ),
                ("thank_you_text", models.TextField(blank=True, help_text="Thank you message after survey submission")),
                (
                    "trigger_on_ticket_resolution",
                    models.BooleanField(default=False, help_text="Automatically send when ticket is resolved"),
                ),
                (
                    "trigger_on_project_completion",
                    models.BooleanField(default=False, help_text="Automatically send when project is completed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this survey belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "support_surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ticket_number",
                    models.CharField(help_text="Unique ticket number (auto-generated)", max_length=50, unique=True),
                ),
                ("contact_email", models.EmailField(help_text="Contact email for this ticket", max_length=254)),
                ("contact_name", models.CharField(help_text="Contact name", max_length=255)),
                ("subject", models.CharField(help_text="Ticket subject/title", max_length=500)),
                ("description", models.TextField(help_text="Detailed description of the issue")),
                (
                    "priority",
                    models.CharField(
                        choices=[("critical", "Critical"), ("high", "High"), ("normal", "Normal"), ("low", "Low")],
                        default="normal",
                        help_text="Ticket priority level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("open", "Open"),
                            ("pending", "Pending Customer"),
                            ("on_hold", "On Hold"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        help_text="Current ticket status",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("chat", "Chat"),
                            ("portal", "Client Portal"),
                            ("api", "API"),
                            ("other", "Other"),
                        ],
                        default="email",
                        help_text="Channel through which ticket was created",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_team",
                    models.CharField(
                        blank=True,
                        help_text="Team assigned to this ticket (e.g., 'Support', 'Technical')",
                        max_length=100,
                    ),
                ),
                (
                    "first_response_at",
                    models.DateTimeField(blank=True, help_text="When the first staff response was sent", null=True),
                ),
                (
                    "first_response_sla_breached",
                    models.BooleanField(default=False, help_text="Did we breach first response SLA?"),
                ),
                ("resolved_at", models.DateTimeField(blank=True, help_text="When the ticket was resolved", null=True)),
                (
                    "resolution_sla_breached",
                    models.BooleanField(default=False, help_text="Did we breach resolution SLA?"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ticket category (e.g., 'Billing', 'Technical', 'General')",
                        max_length=100,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, help_text="Tags for categorization and search")),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Customer satisfaction rating (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("satisfaction_comment", models.TextField(blank=True, help_text="Customer feedback comment")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned to this ticket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client who submitted the ticket",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="clients.client",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this ticket belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="firm.firm",
                    ),
                ),
                (
                    "related_conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related conversation thread",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="communications.conversation",
                    ),
                ),
                (
                    "sla_policy",
                    models.ForeignKey(
                        blank=True,
                        help_text="SLA policy applied to this ticket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="support.slapolicy",
                    ),
                ),
            ],
            options={
                "db_table": "support_tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact_email", models.EmailField(help_text="Email of respondent", max_length=254)),
                ("contact_name", models.CharField(help_text="Name of respondent", max_length=255)),
                ("answers", models.JSONField(default=dict, help_text="Survey answers keyed by question ID")),
                (
                    "nps_score",
                    models.IntegerField(
                        blank=True,
                        help_text="NPS score (0-10), 0=detractor, 7-8=passive, 9-10=promoter",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "nps_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("detractor", "Detractor (0-6)"),
                            ("passive", "Passive (7-8)"),
                            ("promoter", "Promoter (9-10)"),
                        ],
                        help_text="NPS category based on score",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client who responded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to="clients.client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project that triggered this survey (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to="projects.project",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        help_text="Survey this response belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="support.survey",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ticket that triggered this survey (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to="support.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "support_survey_responses",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(help_text="Comment content")),
                (
                    "is_internal",
                    models.BooleanField(default=False, help_text="Is this an internal note (not visible to customer)?"),
                ),
                (
                    "is_customer_reply",
                    models.BooleanField(default=False, help_text="Was this comment from the customer?"),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, help_text="Customer name if this is a customer reply", max_length=255),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, help_text="Customer email if this is a customer reply", max_length=254
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Staff member who created this comment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="Ticket this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="support.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "support_ticket_comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["ticket", "created_at"], name="support_tic_cre_idx"),
                    models.Index(fields=["created_by", "-created_at"], name="support_cre_cre_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["firm", "status"], name="support_ticket_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["firm", "-created_at"], name="support_fir_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["firm", "priority", "status"], name="support_fir_pri_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["client", "-created_at"], name="support_cli_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["assigned_to", "status"], name="support_ass_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["ticket_number"], name="support_tic_idx"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["survey", "-submitted_at"], name="support_sur_sub_idx"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["client", "-submitted_at"], name="support_cli_sub_idx"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["nps_score"], name="support_nps_score_idx"),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(fields=["nps_category"], name="support_nps_category_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["firm", "status"], name="support_survey_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["firm", "survey_type"], name="support_fir_sur_idx"),
        ),
        migrations.AddIndex(
            model_name="slapolicy",
            index=models.Index(fields=["firm", "priority"], name="support_fir_pri_idx"),
        ),
        migrations.AddIndex(
            model_name="slapolicy",
            index=models.Index(fields=["firm", "is_active"], name="support_fir_is__idx"),
        ),
        migrations.AlterUniqueTogether(
            name="slapolicy",
            unique_together={("firm", "priority")},
        ),
    ]
