from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_engagement_invoice_engagement_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if invoice was generated by scheduler'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_payment_retry_at',
            field=models.DateTimeField(blank=True, help_text='When last payment retry was attempted', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, help_text='When payment attempt failed', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_failure_code',
            field=models.CharField(blank=True, help_text='Processor error code', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_failure_reason',
            field=models.CharField(blank=True, help_text='Reason for payment failure (from processor)', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_retry_count',
            field=models.IntegerField(default=0, help_text='Number of payment retry attempts'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, help_text='End date for billing period (package invoices)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start date for billing period (package invoices)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID for tracking', max_length=255),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['engagement', 'period_start'], name='finance_inv_engagem_989955_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('firm', 'invoice_number'), ('engagement', 'period_start')},
        ),
        migrations.CreateModel(
            name='PaymentDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('under_review', 'Under Review'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], default='opened', max_length=20)),
                ('reason', models.CharField(choices=[('fraudulent', 'Fraudulent'), ('duplicate', 'Duplicate Charge'), ('product_not_received', 'Product/Service Not Received'), ('product_unacceptable', 'Product/Service Unacceptable'), ('credit_not_processed', 'Credit Not Processed'), ('general', 'General')], help_text='Reason for dispute', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount being disputed', max_digits=12)),
                ('stripe_dispute_id', models.CharField(help_text='Stripe Dispute ID', max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe Charge ID', max_length=255)),
                ('opened_at', models.DateTimeField(help_text='When dispute was opened')),
                ('respond_by', models.DateTimeField(blank=True, help_text='Deadline to respond to dispute', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When dispute was closed', null=True)),
                ('evidence_submitted', models.BooleanField(default=False, help_text='Whether evidence was submitted to processor')),
                ('evidence_submitted_at', models.DateTimeField(blank=True, help_text='When evidence was submitted', null=True)),
                ('resolution', models.CharField(blank=True, help_text='Dispute resolution (won/lost)', max_length=20)),
                ('resolution_reason', models.TextField(blank=True, help_text='Reason for resolution (from processor)')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes about dispute (platform use only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(help_text='Firm this dispute belongs to', on_delete=models.CASCADE, related_name='payment_disputes', to='firm.firm')),
                ('invoice', models.ForeignKey(help_text='Invoice being disputed', on_delete=models.CASCADE, related_name='disputes', to='finance.invoice')),
            ],
            options={
                'db_table': 'finance_payment_dispute',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['firm', 'status', '-opened_at'], name='finance_pay_firm_i_3789c7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['invoice', '-opened_at'], name='finance_pay_invoice_242cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['stripe_dispute_id'], name='finance_pay_stripe__1ec124_idx'),
        ),
    ]
