# Generated by Django 4.2.17 on 2026-01-01 04:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0008_contact_engagementline_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0010_profitability_reporting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chargeback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, help_text="Amount charged back", max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted (Refunded)"),
                            ("contested", "Contested"),
                            ("won", "Won (Funds Retained)"),
                            ("lost", "Lost (Funds Reversed)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fraudulent", "Fraudulent"),
                            ("duplicate", "Duplicate"),
                            ("product_not_received", "Product/Service Not Received"),
                            ("product_unacceptable", "Product/Service Unacceptable"),
                            ("subscription_canceled", "Subscription Canceled"),
                            ("credit_not_processed", "Credit Not Processed"),
                            ("general", "General"),
                        ],
                        help_text="Reason for chargeback",
                        max_length=50,
                    ),
                ),
                (
                    "stripe_chargeback_id",
                    models.CharField(help_text="Stripe Chargeback/Dispute ID", max_length=255, unique=True),
                ),
                ("stripe_charge_id", models.CharField(help_text="Original Stripe Charge ID", max_length=255)),
                ("initiated_at", models.DateTimeField(help_text="When customer initiated chargeback")),
                (
                    "respond_by",
                    models.DateTimeField(blank=True, help_text="Deadline to respond with evidence", null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, help_text="When chargeback was resolved", null=True)),
                ("evidence_submitted", models.BooleanField(default=False, help_text="Whether evidence was submitted")),
                ("evidence_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, help_text="Notes on chargeback resolution")),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Chargeback fee charged by processor",
                        max_digits=10,
                    ),
                ),
                (
                    "funds_reversed",
                    models.BooleanField(default=False, help_text="Whether funds were reversed to customer"),
                ),
                ("internal_notes", models.TextField(blank=True, help_text="Internal notes (platform use only)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_chargeback",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentFailure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount_attempted",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount that was attempted to charge", max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "failure_code",
                    models.CharField(
                        choices=[
                            ("card_declined", "Card Declined"),
                            ("insufficient_funds", "Insufficient Funds"),
                            ("expired_card", "Expired Card"),
                            ("incorrect_cvc", "Incorrect CVC"),
                            ("processing_error", "Processing Error"),
                            ("authentication_required", "Authentication Required"),
                            ("network_error", "Network Error"),
                            ("other", "Other"),
                        ],
                        help_text="Reason code for failure",
                        max_length=50,
                    ),
                ),
                ("failure_message", models.TextField(help_text="Human-readable failure message (no sensitive data)")),
                (
                    "stripe_payment_intent_id",
                    models.CharField(help_text="Stripe PaymentIntent ID for reference", max_length=255),
                ),
                ("stripe_error_code", models.CharField(blank=True, help_text="Stripe error code", max_length=100)),
                ("retry_count", models.IntegerField(default=0, help_text="Number of retry attempts made")),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, help_text="When to retry payment (if automated)", null=True),
                ),
                (
                    "max_retries_reached",
                    models.BooleanField(default=False, help_text="Whether max retries have been attempted"),
                ),
                (
                    "customer_notified",
                    models.BooleanField(default=False, help_text="Whether customer was notified of failure"),
                ),
                ("notified_at", models.DateTimeField(blank=True, help_text="When customer was notified", null=True)),
                ("resolved", models.BooleanField(default=False, help_text="Whether payment was eventually successful")),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, help_text="When payment succeeded after failure", null=True),
                ),
                ("failed_at", models.DateTimeField(default=django.utils.timezone.now, help_text="When payment failed")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_payment_failure",
                "ordering": ["-failed_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_event_id",
                    models.CharField(
                        help_text="Stripe webhook event ID (unique identifier from Stripe)", max_length=255, unique=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Stripe event type (e.g., payment_intent.succeeded, charge.dispute.created)",
                        max_length=100,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True, help_text="When this event was processed")),
                (
                    "processed_successfully",
                    models.BooleanField(default=True, help_text="Whether event was processed successfully"),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if processing failed")),
                ("event_data", models.JSONField(default=dict, help_text="Raw Stripe event data (for audit/debugging)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stripe Webhook Event",
                "verbose_name_plural": "Stripe Webhook Events",
                "db_table": "finance_stripe_webhook_events",
                "ordering": ["-processed_at", "-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="billingallocation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="billingallocation",
            name="created_by_actor",
        ),
        migrations.RemoveField(
            model_name="billingallocation",
            name="firm",
        ),
        migrations.RemoveField(
            model_name="billingallocation",
            name="from_entry",
        ),
        migrations.RemoveField(
            model_name="billingallocation",
            name="to_entry",
        ),
        migrations.AlterUniqueTogether(
            name="billingledgerentry",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="billingledgerentry",
            name="account",
        ),
        migrations.RemoveField(
            model_name="billingledgerentry",
            name="created_by_actor",
        ),
        migrations.RemoveField(
            model_name="billingledgerentry",
            name="engagement",
        ),
        migrations.RemoveField(
            model_name="billingledgerentry",
            name="firm",
        ),
        migrations.RemoveField(
            model_name="billingledgerentry",
            name="invoice",
        ),
        migrations.RemoveConstraint(
            model_name="payment",
            name="finance_payment_firm_number_unique",
        ),
        migrations.RemoveConstraint(
            model_name="servicelineprofitability",
            name="finance_service_line_profitability_firm_name_period_start_period_end_uniq",
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="finance_bill_due_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="finance_bill_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="creditledgerentry",
            name="finance_credit_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_firm_client_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_due_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_engagement_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="finance_inv_client_status_idx",
        ),
        migrations.RenameIndex(
            model_name="creditledgerentry",
            new_name="finance_fir_cli_cre_idx",
            old_name="finance_cre_firm_id_156789_idx",
        ),
        migrations.RenameIndex(
            model_name="creditledgerentry",
            new_name="finance_fir_cli_cre_idx",
            old_name="finance_credit_firm_client_idx",
        ),
        migrations.RenameIndex(
            model_name="creditledgerentry",
            new_name="finance_cli_ent_cre_idx",
            old_name="finance_cre_client__ddb639_idx",
        ),
        migrations.RenameIndex(
            model_name="creditledgerentry",
            new_name="finance_sou_idx",
            old_name="finance_cre_source__dd06aa_idx",
        ),
        migrations.RenameIndex(
            model_name="creditledgerentry",
            new_name="finance_app_idx",
            old_name="finance_cre_applied_60f77c_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="finance_eng_per_idx",
            old_name="finance_inv_engagem_989955_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="finance_fir_pay_num_idx",
            old_name="finance_fir_pay_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentallocation",
            new_name="finance_all_fir_pay_idx",
            old_name="finance_fir_pay_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentdispute",
            new_name="finance_fir_sta_ope_idx",
            old_name="finance_pay_firm_i_3789c7_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentdispute",
            new_name="finance_inv_ope_idx",
            old_name="finance_pay_invoice_242cf8_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentdispute",
            new_name="finance_dis_str_idx",
            old_name="finance_pay_stripe__1ec124_idx",
        ),
        migrations.AddField(
            model_name="bill",
            name="rejected_at",
            field=models.DateTimeField(blank=True, help_text="When bill was rejected", null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who rejected this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="rejection_reason",
            field=models.TextField(blank=True, help_text="Reason for bill rejection"),
        ),
        migrations.AddField(
            model_name="bill",
            name="scheduled_payment_date",
            field=models.DateField(blank=True, help_text="Date when payment is scheduled", null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="validated_at",
            field=models.DateTimeField(blank=True, help_text="When bill was validated", null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who validated this bill (checked for accuracy)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="validation_notes",
            field=models.TextField(blank=True, help_text="Notes from validation process"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="dunning_level",
            field=models.IntegerField(
                default=0,
                help_text="Current dunning level (0=no reminders, 1=first reminder, 2=second, 3=final, 4=collections)",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="dunning_pause_reason",
            field=models.TextField(
                blank=True, help_text="Reason for pausing dunning (e.g., payment plan agreed, dispute)"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="dunning_paused",
            field=models.BooleanField(default=False, help_text="Whether dunning reminders are paused for this invoice"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_dunning_sent_at",
            field=models.DateTimeField(blank=True, help_text="When last dunning reminder was sent", null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="milestone_reference",
            field=models.IntegerField(
                blank=True, help_text="Index of milestone in project.milestones that triggered this invoice", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="approved_at",
            field=models.DateTimeField(blank=True, help_text="When bill was approved for payment", null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this bill for payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("validated", "Validated"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled for Payment"),
                    ("paid", "Paid"),
                    ("partial", "Partially Paid"),
                    ("overdue", "Overdue"),
                    ("disputed", "Disputed"),
                    ("rejected", "Rejected"),
                ],
                default="received",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent to Client"),
                    ("paid", "Paid"),
                    ("partial", "Partially Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Payment Failed"),
                    ("disputed", "Under Dispute"),
                    ("refunded", "Refunded"),
                    ("charged_back", "Charged Back"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="allocation_date",
            field=models.DateField(default=django.utils.timezone.now, help_text="Date when allocation was made"),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payment_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("firm", "payment_number")},
        ),
        migrations.AlterUniqueTogether(
            name="servicelineprofitability",
            unique_together={("firm", "name", "period_start", "period_end")},
        ),
        migrations.DeleteModel(
            name="BillingAllocation",
        ),
        migrations.DeleteModel(
            name="BillingLedgerEntry",
        ),
        migrations.AddField(
            model_name="stripewebhookevent",
            name="dispute",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment dispute related to this event (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="finance.paymentdispute",
            ),
        ),
        migrations.AddField(
            model_name="stripewebhookevent",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm this webhook event belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_webhook_events",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="stripewebhookevent",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Invoice related to this event (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="stripewebhookevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment related to this event (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="finance.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentfailure",
            name="client",
            field=models.ForeignKey(
                help_text="Client whose payment failed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_failures",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="paymentfailure",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm this failure belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_failures",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="paymentfailure",
            name="invoice",
            field=models.ForeignKey(
                help_text="Invoice that failed to pay",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_failures",
                to="finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="chargeback",
            name="client",
            field=models.ForeignKey(
                help_text="Client who initiated chargeback",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chargebacks",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="chargeback",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm this chargeback belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chargebacks",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="chargeback",
            name="invoice",
            field=models.ForeignKey(
                help_text="Invoice that was charged back",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chargebacks",
                to="finance.invoice",
            ),
        ),
        migrations.AddIndex(
            model_name="stripewebhookevent",
            index=models.Index(fields=["firm", "event_type"], name="finance_fir_evt_idx"),
        ),
        migrations.AddIndex(
            model_name="stripewebhookevent",
            index=models.Index(fields=["firm", "processed_at"], name="finance_fir_pro_idx"),
        ),
        migrations.AddIndex(
            model_name="stripewebhookevent",
            index=models.Index(fields=["stripe_event_id"], name="finance_evt_id_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentfailure",
            index=models.Index(fields=["firm", "resolved", "-failed_at"], name="finance_fir_res_fai_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentfailure",
            index=models.Index(fields=["invoice", "-failed_at"], name="finance_inv_fai_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentfailure",
            index=models.Index(fields=["client", "-failed_at"], name="finance_cli_fai_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentfailure",
            index=models.Index(fields=["stripe_payment_intent_id"], name="finance_fai_str_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentfailure",
            index=models.Index(fields=["next_retry_at"], name="finance_nex_idx"),
        ),
        migrations.AddIndex(
            model_name="chargeback",
            index=models.Index(fields=["firm", "status", "-initiated_at"], name="finance_fir_sta_ini_idx"),
        ),
        migrations.AddIndex(
            model_name="chargeback",
            index=models.Index(fields=["invoice", "-initiated_at"], name="finance_inv_ini_idx"),
        ),
        migrations.AddIndex(
            model_name="chargeback",
            index=models.Index(fields=["client", "-initiated_at"], name="finance_cli_ini_idx"),
        ),
        migrations.AddIndex(
            model_name="chargeback",
            index=models.Index(fields=["stripe_chargeback_id"], name="finance_chb_str_idx"),
        ),
    ]
