# Generated by Django 4.2.17 on 2026-01-01 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SAMLConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Friendly name for this SAML configuration", max_length=255)),
                ("sp_entity_id", models.CharField(help_text="Service Provider Entity ID (URL)", max_length=500)),
                ("sp_public_cert", models.TextField(blank=True, help_text="SP X.509 public certificate (PEM format)")),
                ("sp_private_key", models.TextField(blank=True, help_text="SP private key (PEM format)")),
                ("idp_entity_id", models.CharField(help_text="Identity Provider Entity ID", max_length=500)),
                ("idp_sso_url", models.URLField(help_text="IdP Single Sign-On URL")),
                ("idp_slo_url", models.URLField(blank=True, help_text="IdP Single Logout URL")),
                ("idp_x509_cert", models.TextField(help_text="IdP X.509 certificate (PEM format)")),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map SAML attributes to User model fields. Example: {'email': 'mail', 'first_name': 'givenName'}",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Only one configuration can be active at a time"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SAML Configuration",
                "verbose_name_plural": "SAML Configurations",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMFAProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="Phone number for SMS-based MFA", max_length=20),
                ),
                ("sms_mfa_enabled", models.BooleanField(default=False, help_text="Whether SMS-based MFA is enabled")),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Link to Django User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User MFA Profile",
                "verbose_name_plural": "User MFA Profiles",
            },
        ),
    ]
