# Generated by Django 4.2.17 on 2026-01-02 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ADSyncConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "server_url",
                    models.CharField(help_text="LDAPS URL (e.g., ldaps://ad.company.com:636)", max_length=255),
                ),
                (
                    "service_account_dn",
                    models.CharField(
                        help_text="Service account Distinguished Name (e.g., CN=ServiceAccount,OU=Service Accounts,DC=company,DC=com)",
                        max_length=500,
                    ),
                ),
                (
                    "encrypted_password",
                    models.TextField(help_text="Encrypted service account password (stored encrypted at rest)"),
                ),
                (
                    "base_dn",
                    models.CharField(
                        help_text="Base Distinguished Name for searches (e.g., DC=company,DC=com)", max_length=500
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False, help_text="Whether AD sync is currently enabled")),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("full", "Full Sync"), ("delta", "Delta/Incremental Sync")],
                        default="delta",
                        help_text="Type of sync: full or delta/incremental",
                        max_length=20,
                    ),
                ),
                (
                    "sync_schedule",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        help_text="How often to sync automatically",
                        max_length=20,
                    ),
                ),
                (
                    "ou_filter",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Specific OU to sync from (e.g., OU=Employees,DC=company,DC=com)",
                        max_length=500,
                    ),
                ),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Map AD attributes to User model fields (e.g., {"email": "mail", "first_name": "givenName"})',
                    ),
                ),
                (
                    "auto_disable_users",
                    models.BooleanField(
                        default=True, help_text="Automatically disable users when their AD account is disabled"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, help_text="Timestamp of last successful sync", null=True),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error"), ("pending", "Pending")],
                        default="pending",
                        help_text="Status of last sync attempt",
                        max_length=20,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True, help_text="Error message from last failed sync")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ad_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.OneToOneField(
                        help_text="Firm this AD configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_sync_config",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD Sync Configuration",
                "verbose_name_plural": "AD Sync Configurations",
                "db_table": "ad_sync_config",
            },
        ),
        migrations.CreateModel(
            name="ADUserMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ad_guid",
                    models.CharField(
                        help_text="AD objectGUID (used for tracking across renames)", max_length=36, unique=True
                    ),
                ),
                ("ad_upn", models.CharField(blank=True, help_text="AD userPrincipalName", max_length=255)),
                (
                    "ad_sam_account",
                    models.CharField(blank=True, help_text="AD sAMAccountName (username)", max_length=255),
                ),
                ("ad_dn", models.CharField(help_text="AD Distinguished Name", max_length=500)),
                (
                    "first_synced_at",
                    models.DateTimeField(auto_now_add=True, help_text="When user was first synced from AD"),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True, help_text="When user was last synced from AD")),
                ("ad_last_modified", models.DateTimeField(blank=True, help_text="AD whenChanged timestamp", null=True)),
                (
                    "is_ad_managed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this user is managed by AD sync (cannot be edited manually if True)",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_user_mappings",
                        to="firm.firm",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Platform user this mapping belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_mapping",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AD User Mapping",
                "verbose_name_plural": "AD User Mappings",
                "db_table": "ad_user_mapping",
                "indexes": [
                    models.Index(fields=["firm", "is_ad_managed"], name="ad_usr_firm_idx"),
                    models.Index(fields=["ad_guid"], name="ad_usr_guid_idx"),
                ],
                "unique_together": {("firm", "ad_guid")},
            },
        ),
        migrations.CreateModel(
            name="ADSyncLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("full", "Full Sync"), ("delta", "Delta Sync"), ("manual", "Manual Sync")],
                        help_text="Type of sync that was performed",
                        max_length=20,
                    ),
                ),
                ("users_found", models.IntegerField(default=0, help_text="Number of users found in AD")),
                ("users_created", models.IntegerField(default=0, help_text="Number of new users created")),
                ("users_updated", models.IntegerField(default=0, help_text="Number of existing users updated")),
                ("users_disabled", models.IntegerField(default=0, help_text="Number of users disabled")),
                (
                    "users_skipped",
                    models.IntegerField(default=0, help_text="Number of users skipped (e.g., missing email)"),
                ),
                ("groups_synced", models.IntegerField(default=0, help_text="Number of AD groups synchronized")),
                (
                    "group_members_synced",
                    models.IntegerField(default=0, help_text="Number of group memberships synchronized"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error"), ("partial", "Partial Success")],
                        help_text="Overall sync status",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error details if sync failed")),
                ("duration_seconds", models.IntegerField(help_text="How long the sync took in seconds")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When sync completed (null if still running)", null=True
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this sync log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_sync_logs",
                        to="firm.firm",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who manually triggered this sync (null for scheduled syncs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_ad_syncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AD Sync Log",
                "verbose_name_plural": "AD Sync Logs",
                "db_table": "ad_sync_log",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["firm", "-started_at"], name="ad_firm_start_idx"),
                    models.Index(fields=["status"], name="ad_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ADProvisioningRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Descriptive name for this rule", max_length=255)),
                ("is_enabled", models.BooleanField(default=True, help_text="Whether this rule is currently active")),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Rule priority (lower number = higher priority). Rules are evaluated in order.",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("ad_group", "AD Group Membership"),
                            ("ou_path", "OU Path Match"),
                            ("attribute_value", "Attribute Value Match"),
                            ("always", "Always Apply"),
                        ],
                        help_text="Type of condition to evaluate",
                        max_length=50,
                    ),
                ),
                (
                    "condition_value",
                    models.JSONField(
                        default=dict,
                        help_text='Condition parameters (e.g., {"group_dn": "CN=Developers,OU=Groups,DC=company,DC=com"})',
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("assign_role", "Assign Firm Role"),
                            ("skip_user", "Skip User Creation"),
                            ("set_active", "Set User Active/Inactive"),
                        ],
                        help_text="Action to perform when condition matches",
                        max_length=50,
                    ),
                ),
                (
                    "action_value",
                    models.JSONField(
                        default=dict, help_text='Action parameters (e.g., {"role": "staff", "is_active": true})'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this rule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ad_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this rule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_provisioning_rules",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD Provisioning Rule",
                "verbose_name_plural": "AD Provisioning Rules",
                "db_table": "ad_provisioning_rule",
                "ordering": ["priority", "name"],
                "indexes": [models.Index(fields=["firm", "is_enabled", "priority"], name="ad_rule_prio_idx")],
            },
        ),
        migrations.CreateModel(
            name="ADGroupMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ad_group_dn",
                    models.CharField(
                        help_text="AD group Distinguished Name (e.g., CN=Developers,OU=Groups,DC=company,DC=com)",
                        max_length=500,
                    ),
                ),
                ("ad_group_name", models.CharField(help_text="AD group common name for display", max_length=255)),
                ("ad_group_guid", models.CharField(blank=True, help_text="AD group GUID for tracking", max_length=36)),
                ("is_enabled", models.BooleanField(default=True, help_text="Whether to sync this group")),
                ("sync_members", models.BooleanField(default=True, help_text="Whether to sync group member list")),
                (
                    "assign_role",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Automatically assign this firm role to group members",
                        max_length=20,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, help_text="When this group was last synced", null=True),
                ),
                (
                    "member_count",
                    models.IntegerField(default=0, help_text="Number of members in this group (from last sync)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this mapping belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_group_mappings",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD Group Mapping",
                "verbose_name_plural": "AD Group Mappings",
                "db_table": "ad_group_mapping",
                "indexes": [models.Index(fields=["firm", "is_enabled"], name="ad_grp_firm_idx")],
                "unique_together": {("firm", "ad_group_dn")},
            },
        ),
    ]
