# Generated by Django 4.2.8 on 2025-12-24 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to specific project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this bill belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to project if this is a project expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["firm", "account", "transaction_date"],
                name="finance_led_firm_id_d51e38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["firm", "transaction_group_id"],
                name="finance_led_firm_id_6780f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["firm", "-transaction_date"],
                name="finance_led_firm_id_401959_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["firm", "entry_type"], name="finance_led_firm_id_429ebc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["firm", "status"], name="finance_inv_firm_id_65cda3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["firm", "client", "status"],
                name="finance_inv_firm_id_c034d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["firm", "invoice_number"], name="finance_inv_firm_id_83426d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["firm", "due_date"], name="finance_inv_firm_id_1ec845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["firm", "-issue_date"], name="finance_inv_firm_id_1a7c2d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("firm", "invoice_number")},
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["firm", "status"], name="finance_bil_firm_id_163b0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["firm", "vendor_name", "status"],
                name="finance_bil_firm_id_90f01a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["firm", "reference_number"],
                name="finance_bil_firm_id_83abc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["firm", "due_date"], name="finance_bil_firm_id_aba601_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["firm", "-bill_date"], name="finance_bil_firm_id_0c14a4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together={("firm", "reference_number")},
        ),
    ]
