# Generated by Django 4.2.8 on 2025-12-25 09:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("firm", "0004_auditevent"),
        ("clients", "0006_client_autopay_activated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="engagement",
            field=models.ForeignKey(
                blank=True,
                help_text="Engagement this invoice belongs to (Master Admin can override)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="clients.clientengagement",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="engagement_override",
            field=models.BooleanField(
                default=False, help_text="True if Master Admin overrode default engagement linkage"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="engagement_override_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Master Admin who overrode engagement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_engagement_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="engagement_override_reason",
            field=models.TextField(blank=True, help_text="Reason for engagement override (required if overridden)"),
        ),
        migrations.CreateModel(
            name="CreditLedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("credit", "Credit Added"), ("debit", "Credit Applied/Used")],
                        help_text="Credit (added) or Debit (used)",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of credit (always positive)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("overpayment", "Overpayment"),
                            ("refund", "Refund"),
                            ("goodwill", "Goodwill Credit"),
                            ("promotional", "Promotional Credit"),
                            ("correction", "Billing Correction"),
                        ],
                        help_text="How credit was created (for credit entries)",
                        max_length=20,
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invoice_payment", "Applied to Invoice"),
                            ("partial_payment", "Partial Payment"),
                            ("expired", "Credit Expired"),
                            ("refunded", "Refunded to Client"),
                        ],
                        help_text="How credit was used (for debit entries)",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Description of credit creation or use")),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for credit (required for goodwill/correction credits)"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="When this credit expires (if applicable)", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audit_event_id",
                    models.BigIntegerField(
                        blank=True, help_text="Link to audit event for this credit operation", null=True
                    ),
                ),
                (
                    "applied_to_invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Invoice this credit was applied to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_applications",
                        to="finance.invoice",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved this credit (for goodwill/correction)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this credit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledger",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Who created this credit entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this credit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledger",
                        to="firm.firm",
                    ),
                ),
                (
                    "source_invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Invoice that generated this credit (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_sources",
                        to="finance.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Credit Ledger Entries",
                "db_table": "finance_credit_ledger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["firm", "client", "-created_at"], name="finance_cre_firm_id_156789_idx"),
                    models.Index(fields=["client", "entry_type", "-created_at"], name="finance_cre_client__ddb639_idx"),
                    models.Index(fields=["source_invoice"], name="finance_cre_source__dd06aa_idx"),
                    models.Index(fields=["applied_to_invoice"], name="finance_cre_applied_60f77c_idx"),
                ],
            },
        ),
    ]
