# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrchestrationDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Human-readable name for this orchestration", max_length=255)),
                ("code", models.CharField(help_text="Stable code identifier", max_length=100)),
                ("version", models.IntegerField(default=1, help_text="Monotonic version number")),
                ("steps_json", models.JSONField(default=list, help_text="Step definitions array")),
                ("policies", models.JSONField(default=dict, help_text="Timeout, retry, concurrency policies")),
                (
                    "input_schema",
                    models.JSONField(blank=True, default=dict, help_text="JSON schema for input validation"),
                ),
                (
                    "output_schema",
                    models.JSONField(blank=True, default=dict, help_text="JSON schema for output validation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("deprecated", "Deprecated")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_orchestration_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this definition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_definitions",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_definition",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="OrchestrationExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("definition_version", models.IntegerField(help_text="Version at time of execution")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("waiting_approval", "Waiting Approval"),
                            ("paused", "Paused"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "target_object_type",
                    models.CharField(
                        choices=[
                            ("engagement", "Engagement"),
                            ("work_item", "WorkItem"),
                            ("task", "Task"),
                            ("invoice", "Invoice"),
                            ("document", "Document"),
                        ],
                        help_text="Type of object being orchestrated",
                        max_length=50,
                    ),
                ),
                ("target_object_id", models.IntegerField(help_text="ID of target object")),
                ("input_data", models.JSONField(default=dict, help_text="Validated input snapshot")),
                ("output_data", models.JSONField(blank=True, default=dict, help_text="Execution output")),
                (
                    "idempotency_key",
                    models.CharField(help_text="Execution-level idempotency key", max_length=64, unique=True),
                ),
                ("correlation_id", models.CharField(help_text="Root correlation ID", max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.IntegerField(default=1, help_text="Number of execution restart attempts")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="orchestration.orchestrationdefinition",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_executions",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StepExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_id", models.CharField(help_text="Step ID from definition", max_length=100)),
                ("step_name", models.CharField(help_text="Human-readable step name", max_length=255)),
                ("attempt_number", models.IntegerField(default=1, help_text="Attempt number for this step")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("timed_out", "Timed Out"),
                            ("skipped", "Skipped"),
                            ("awaiting_approval", "Awaiting Approval"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRANSIENT", "Transient Error"),
                            ("RETRYABLE", "Retryable Error"),
                            ("NON_RETRYABLE", "Non-Retryable Error"),
                            ("RATE_LIMITED", "Rate Limited"),
                            ("DEPENDENCY_FAILED", "Dependency Failed"),
                            ("COMPENSATION_REQUIRED", "Compensation Required"),
                        ],
                        help_text="Classified error type per docs/03-reference/requirements/DOC-11.md section 4",
                        max_length=50,
                    ),
                ),
                ("error_summary", models.TextField(blank=True, help_text="Redacted error summary")),
                ("retry_after_at", models.DateTimeField(blank=True, help_text="When to retry this step", null=True)),
                ("idempotency_key", models.CharField(help_text="Step-level idempotency key", max_length=64)),
                ("result_data", models.JSONField(blank=True, default=dict, help_text="Step result (bounded)")),
                (
                    "logs_ref",
                    models.CharField(blank=True, help_text="Optional pointer to external logs", max_length=255),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="orchestration.orchestrationexecution",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="step_executions", to="firm.firm"
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_step_execution",
                "ordering": ["execution", "step_id", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="OrchestrationDLQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("max_retries_exceeded", "Max Retries Exceeded"),
                            ("non_retryable_error", "Non-Retryable Error"),
                            ("compensation_required", "Compensation Required"),
                            ("timeout_exceeded", "Timeout Exceeded"),
                        ],
                        help_text="Why this was sent to DLQ",
                        max_length=50,
                    ),
                ),
                ("error_class", models.CharField(help_text="Error classification", max_length=50)),
                ("error_summary", models.TextField(help_text="Redacted error summary")),
                ("resolved", models.BooleanField(default=False, help_text="Has this DLQ item been resolved?")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, help_text="Notes on how this was resolved")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlq_entries",
                        to="orchestration.orchestrationexecution",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orchestration_dlq", to="firm.firm"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_dlq_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlq_entries",
                        to="orchestration.stepexecution",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_dlq",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="stepexecution",
            index=models.Index(fields=["firm", "execution", "step_id"], name="orchestrat_fir_exe_ste_idx"),
        ),
        migrations.AddIndex(
            model_name="stepexecution",
            index=models.Index(fields=["firm", "status"], name="orchestrat_stp_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="stepexecution",
            index=models.Index(fields=["idempotency_key"], name="orchestrat_stp_ide_idx"),
        ),
        migrations.AddIndex(
            model_name="stepexecution",
            index=models.Index(fields=["retry_after_at"], name="orchestrat_ret_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationexecution",
            index=models.Index(fields=["firm", "status", "-started_at"], name="orchestrat_fir_sta_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationexecution",
            index=models.Index(fields=["firm", "definition", "-started_at"], name="orchestrat_fir_def_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationexecution",
            index=models.Index(fields=["idempotency_key"], name="orchestrat_exe_ide_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationexecution",
            index=models.Index(fields=["correlation_id"], name="orchestrat_cor_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationexecution",
            index=models.Index(fields=["target_object_type", "target_object_id"], name="orchestrat_tar_tar_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationdlq",
            index=models.Index(fields=["firm", "resolved", "-created_at"], name="orchestrat_fir_res_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationdlq",
            index=models.Index(fields=["execution"], name="orchestrat_exe_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationdefinition",
            index=models.Index(fields=["firm", "code", "-version"], name="orchestrat_fir_cod_ver_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestrationdefinition",
            index=models.Index(fields=["firm", "status"], name="orchestrat_def_fir_sta_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="orchestrationdefinition",
            unique_together={("firm", "code", "version")},
        ),
    ]
