# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0008_contact_engagementline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0006_activity_product_productconfiguration_productoption_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        ("marketing", "0002_rename_mkt_idx_marketing_cam_sta_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Campaign name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Campaign description")),
                ("message_content", models.TextField(help_text="Message content (copied from template or custom)")),
                (
                    "recipient_list",
                    models.JSONField(
                        blank=True, default=list, help_text="Manual list of phone numbers if not using segment"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="When to send campaign (null = send immediately)", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, help_text="When campaign sending started", null=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When campaign sending completed", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        help_text="Campaign status",
                        max_length=20,
                    ),
                ),
                ("recipients_total", models.IntegerField(default=0, help_text="Total number of recipients")),
                ("messages_sent", models.IntegerField(default=0, help_text="Messages successfully sent")),
                ("messages_delivered", models.IntegerField(default=0, help_text="Messages confirmed delivered")),
                ("messages_failed", models.IntegerField(default=0, help_text="Messages that failed to send")),
                ("replies_received", models.IntegerField(default=0, help_text="Replies received")),
                (
                    "opt_outs_received",
                    models.IntegerField(default=0, help_text="Opt-outs received (STOP, UNSUBSCRIBE, etc.)"),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, help_text="Total cost of campaign", max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this campaign",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sms_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this campaign belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_campaigns",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "sms_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "their_number",
                    models.CharField(
                        help_text="Their phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in E.164 format (e.g., +14155552671)",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed"), ("archived", "Archived")],
                        default="active",
                        help_text="Conversation status",
                        max_length=20,
                    ),
                ),
                ("is_opt_out", models.BooleanField(default=False, help_text="Whether contact has opted out of SMS")),
                ("message_count", models.IntegerField(default=0, help_text="Total message count in conversation")),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, help_text="When last message was sent/received", null=True),
                ),
                (
                    "last_message_from_us",
                    models.BooleanField(default=False, help_text="Whether last message was from us (vs. from them)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this conversation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_sms_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_conversations",
                        to="clients.contact",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this conversation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_conversations",
                        to="firm.firm",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_conversations",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "db_table": "sms_conversations",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Template name", max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("campaign", "Campaign"),
                            ("notification", "Notification"),
                            ("reminder", "Reminder"),
                            ("confirmation", "Confirmation"),
                            ("alert", "Alert"),
                            ("custom", "Custom"),
                        ],
                        help_text="Template type",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message content with variables ({{contact_name}}, {{company_name}}, etc.)",
                        max_length=1600,
                    ),
                ),
                (
                    "character_count",
                    models.IntegerField(default=0, help_text="Character count (without variable replacement)"),
                ),
                (
                    "estimated_segments",
                    models.IntegerField(default=1, help_text="Estimated SMS segments (160 chars per segment)"),
                ),
                ("times_used", models.IntegerField(default=0, help_text="Number of times this template has been used")),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, help_text="When this template was last used", null=True),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this template is active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sms_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_templates",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "sms_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SMSPhoneNumber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number in E.164 format (e.g., +14155552671)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in E.164 format (e.g., +14155552671)",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "friendly_name",
                    models.CharField(
                        blank=True,
                        help_text='Friendly name for this number (e.g., "Main Support Line")',
                        max_length=100,
                    ),
                ),
                (
                    "provider",
                    models.CharField(default="twilio", help_text="SMS provider (twilio, etc.)", max_length=20),
                ),
                (
                    "provider_sid",
                    models.CharField(blank=True, help_text="Provider-specific identifier (Twilio SID)", max_length=100),
                ),
                ("can_send_sms", models.BooleanField(default=True, help_text="Whether this number can send SMS")),
                ("can_receive_sms", models.BooleanField(default=True, help_text="Whether this number can receive SMS")),
                (
                    "can_send_mms",
                    models.BooleanField(default=False, help_text="Whether this number can send MMS (images)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending_verification", "Pending Verification"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending_verification",
                        help_text="Phone number status",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Whether this is the default number for the firm"),
                ),
                ("messages_sent", models.IntegerField(default=0, help_text="Total messages sent from this number")),
                (
                    "messages_received",
                    models.IntegerField(default=0, help_text="Total messages received by this number"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, help_text="When this number was last used", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this phone number belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_phone_numbers",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "sms_phone_numbers",
                "ordering": ["-is_default", "phone_number"],
            },
        ),
        migrations.CreateModel(
            name="SMSOptOut",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number that opted out",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in E.164 format (e.g., +14155552671)",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                    ),
                ),
                ("opted_out_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opt_out_message",
                    models.TextField(
                        blank=True, help_text="The message they sent to opt out (STOP, UNSUBSCRIBE, etc.)"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_opt_outs",
                        to="clients.contact",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conversation where opt-out occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opt_outs",
                        to="sms.smsconversation",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this opt-out belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_opt_outs",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "sms_opt_outs",
                "ordering": ["-opted_out_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "to_number",
                    models.CharField(
                        help_text="Recipient phone number in E.164 format",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in E.164 format (e.g., +14155552671)",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound (Sent)"), ("inbound", "Inbound (Received)")],
                        help_text="Message direction",
                        max_length=10,
                    ),
                ),
                ("message_body", models.TextField(help_text="Message content")),
                ("media_urls", models.JSONField(blank=True, default=list, help_text="URLs of attached media (MMS)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("undelivered", "Undelivered"),
                            ("received", "Received"),
                        ],
                        default="queued",
                        help_text="Message status",
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, help_text="Error code if failed", max_length=20)),
                ("error_message", models.TextField(blank=True, help_text="Error message if failed")),
                (
                    "provider_message_sid",
                    models.CharField(blank=True, help_text="Provider message ID (Twilio SID)", max_length=100),
                ),
                ("provider_status", models.CharField(blank=True, help_text="Provider-specific status", max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Cost per message (in provider currency)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_currency",
                    models.CharField(default="USD", help_text="Currency code (USD, EUR, etc.)", max_length=3),
                ),
                ("sent_at", models.DateTimeField(blank=True, help_text="When message was sent", null=True)),
                ("delivered_at", models.DateTimeField(blank=True, help_text="When message was delivered", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campaign this message belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="sms.smscampaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contact associated with this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_messages",
                        to="clients.contact",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conversation this message belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="sms.smsconversation",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_messages",
                        to="firm.firm",
                    ),
                ),
                (
                    "from_number",
                    models.ForeignKey(
                        help_text="Phone number message was sent from (our number)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to="sms.smsphonenumber",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lead associated with this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_messages",
                        to="crm.lead",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent this message (null if automated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_sms_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sms_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="smsconversation",
            name="our_number",
            field=models.ForeignKey(
                help_text="Our phone number in this conversation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="sms.smsphonenumber",
            ),
        ),
        migrations.AddField(
            model_name="smscampaign",
            name="from_number",
            field=models.ForeignKey(
                help_text="Phone number to send from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="sms.smsphonenumber",
            ),
        ),
        migrations.AddField(
            model_name="smscampaign",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment to send to (or manual list)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sms_campaigns",
                to="marketing.segment",
            ),
        ),
        migrations.AddField(
            model_name="smscampaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="SMS template used",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="sms.smstemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="smstemplate",
            index=models.Index(fields=["firm", "template_type"], name="sms_fir_tem_idx"),
        ),
        migrations.AddIndex(
            model_name="smstemplate",
            index=models.Index(fields=["firm", "is_active"], name="sms_template_fir_is__idx"),
        ),
        migrations.AddIndex(
            model_name="smsphonenumber",
            index=models.Index(fields=["firm", "status"], name="sms_phone_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="smsphonenumber",
            index=models.Index(fields=["firm", "is_default"], name="sms_phone_fir_is__idx"),
        ),
        migrations.AddIndex(
            model_name="smsphonenumber",
            index=models.Index(fields=["phone_number"], name="sms_phone_pho_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="smsphonenumber",
            unique_together={("firm", "phone_number")},
        ),
        migrations.AddIndex(
            model_name="smsoptout",
            index=models.Index(fields=["firm", "phone_number"], name="sms_fir_pho_idx"),
        ),
        migrations.AddIndex(
            model_name="smsoptout",
            index=models.Index(fields=["phone_number"], name="sms_optout_pho_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="smsoptout",
            unique_together={("firm", "phone_number")},
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(fields=["firm", "-created_at"], name="sms_message_fir_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(fields=["firm", "to_number", "-created_at"], name="sms_fir_to__cre_idx"),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(fields=["campaign", "-created_at"], name="sms_cam_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(fields=["conversation", "-created_at"], name="sms_con_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(fields=["status"], name="sms_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(fields=["provider_message_sid"], name="sms_pro_idx"),
        ),
        migrations.AddIndex(
            model_name="smsconversation",
            index=models.Index(fields=["firm", "status", "-last_message_at"], name="sms_fir_sta_las_idx"),
        ),
        migrations.AddIndex(
            model_name="smsconversation",
            index=models.Index(fields=["firm", "our_number", "their_number"], name="sms_fir_our_the_idx"),
        ),
        migrations.AddIndex(
            model_name="smsconversation",
            index=models.Index(fields=["assigned_to", "status"], name="sms_ass_sta_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="smsconversation",
            unique_together={("firm", "our_number", "their_number")},
        ),
        migrations.AddIndex(
            model_name="smscampaign",
            index=models.Index(fields=["firm", "status"], name="sms_campaign_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="smscampaign",
            index=models.Index(fields=["firm", "-created_at"], name="sms_campaign_fir_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="smscampaign",
            index=models.Index(fields=["scheduled_at"], name="sms_sch_idx"),
        ),
    ]
