# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0008_contact_engagementline_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Human-readable name for this template", max_length=255)),
                ("code", models.CharField(help_text="Stable code identifier for this template", max_length=100)),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Monotonic version number (increments on each publish)"),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("engagement", "Engagement"),
                            ("engagement_line", "EngagementLine"),
                            ("service_code", "ServiceCode"),
                            ("product_code", "ProductCode"),
                        ],
                        default="engagement",
                        help_text="What object type this template applies to",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description of this delivery template")),
                (
                    "defaults",
                    models.JSONField(default=dict, help_text="Default values for assignees, due offsets, tags, etc."),
                ),
                (
                    "validation_hash",
                    models.CharField(
                        blank=True, help_text="SHA-256 hash of template structure for validation", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("deprecated", "Deprecated")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, help_text="When this template was published", null=True),
                ),
                (
                    "deprecated_at",
                    models.DateTimeField(blank=True, help_text="When this template was deprecated", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_delivery_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_templates",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_template",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "node_id",
                    models.CharField(
                        help_text="Stable identifier within template (e.g., 'task_01', 'gate_approval')", max_length=100
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("milestone", "Milestone"),
                            ("gateway", "Gateway"),
                            ("approval_gate", "Approval Gate"),
                        ],
                        default="task",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Title of the work item", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Detailed description of the work")),
                (
                    "assignee_policy",
                    models.CharField(
                        choices=[("fixed", "Fixed User"), ("role_based", "Role-Based"), ("unassigned", "Unassigned")],
                        default="unassigned",
                        max_length=20,
                    ),
                ),
                (
                    "assignee_role",
                    models.CharField(
                        blank=True, help_text="Role-based assignment (if assignee_policy=role_based)", max_length=100
                    ),
                ),
                (
                    "due_policy",
                    models.CharField(
                        choices=[
                            ("absolute", "Absolute Date"),
                            ("offset_from_activation", "Offset from Activation"),
                            ("offset_from_node_completion", "Offset from Node Completion"),
                        ],
                        default="offset_from_activation",
                        max_length=50,
                    ),
                ),
                ("offset_days", models.IntegerField(default=0, help_text="Offset in days for due date calculation")),
                (
                    "upstream_node_id",
                    models.CharField(
                        blank=True,
                        help_text="Node to offset from (if due_policy=offset_from_node_completion)",
                        max_length=100,
                    ),
                ),
                (
                    "gateway_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("and_join", "AND Join"),
                            ("and_split", "AND Split"),
                            ("or_join", "OR Join"),
                            ("or_split", "OR Split"),
                        ],
                        help_text="Gateway type (if type=gateway)",
                        max_length=20,
                    ),
                ),
                (
                    "approval_policy",
                    models.JSONField(
                        blank=True, default=dict, help_text="Approval policy (who can approve, conditions)"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, help_text="Tags/labels for this node")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="delivery_nodes", to="firm.firm"
                    ),
                ),
                (
                    "fixed_assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fixed assignee (if assignee_policy=fixed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_delivery_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="delivery.deliverytemplate",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_node",
                "ordering": ["node_id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryEdge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_node_id", models.CharField(help_text="Source node ID", max_length=100)),
                ("to_node_id", models.CharField(help_text="Target node ID", max_length=100)),
                (
                    "condition",
                    models.JSONField(blank=True, default=dict, help_text="Optional condition for edge activation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="delivery_edges", to="firm.firm"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="delivery.deliverytemplate",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_edge",
                "ordering": ["from_node_id", "to_node_id"],
            },
        ),
        migrations.CreateModel(
            name="TemplateInstantiation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template_version", models.IntegerField(help_text="Template version at time of instantiation")),
                (
                    "template_hash",
                    models.CharField(help_text="Template validation hash at time of instantiation", max_length=64),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("engagement_activation", "Engagement Activation"),
                            ("engagement_line_activation", "EngagementLine Activation"),
                            ("manual", "Manual Staff Trigger"),
                            ("recurrence", "Recurrence Event"),
                        ],
                        help_text="What triggered this instantiation",
                        max_length=50,
                    ),
                ),
                (
                    "inputs",
                    models.JSONField(
                        default=dict, help_text="Input values used for instantiation (dates, assignees, etc.)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", help_text="Instantiation status (completed/failed/partial)", max_length=20
                    ),
                ),
                ("error_log", models.TextField(blank=True, help_text="Error messages if instantiation failed")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, help_text="Correlation ID for tracking", max_length=64),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_instantiations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_instantiations",
                        to="firm.firm",
                    ),
                ),
                (
                    "target_engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_instantiations",
                        to="clients.clientengagement",
                    ),
                ),
                (
                    "target_engagement_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_instantiations",
                        to="clients.engagementline",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instantiations",
                        to="delivery.deliverytemplate",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_template_instantiation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["firm", "-created_at"], name="delivery_fir_cre_idx"),
                    models.Index(fields=["template", "-created_at"], name="delivery_tem_cre_idx"),
                    models.Index(fields=["target_engagement"], name="delivery_tar_eng_idx"),
                    models.Index(fields=["target_engagement_line"], name="delivery_tar_lin_idx"),
                    models.Index(fields=["correlation_id"], name="delivery_cor_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="deliverytemplate",
            index=models.Index(fields=["firm", "code", "-version"], name="delivery_fir_cod_ver_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverytemplate",
            index=models.Index(fields=["firm", "status"], name="delivery_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverytemplate",
            index=models.Index(fields=["firm", "applies_to"], name="delivery_fir_app_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="deliverytemplate",
            unique_together={("firm", "code", "version")},
        ),
        migrations.AddIndex(
            model_name="deliverynode",
            index=models.Index(fields=["firm", "template"], name="delivery_nod_fir_tem_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverynode",
            index=models.Index(fields=["type"], name="delivery_typ_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="deliverynode",
            unique_together={("template", "node_id")},
        ),
        migrations.AddIndex(
            model_name="deliveryedge",
            index=models.Index(fields=["firm", "template"], name="delivery_edg_fir_tem_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryedge",
            index=models.Index(fields=["from_node_id"], name="delivery_fro_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryedge",
            index=models.Index(fields=["to_node_id"], name="delivery_to__idx"),
        ),
        migrations.AlterUniqueTogether(
            name="deliveryedge",
            unique_together={("template", "from_node_id", "to_node_id")},
        ),
    ]
