# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        ("documents", "0004_document_classification_document_deprecated_at_and_more"),
        ("delivery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sop", "Standard Operating Procedure"),
                            ("training", "Training Manual"),
                            ("kpi", "KPI Definition"),
                            ("playbook", "Playbook"),
                            ("template", "Template/Checklist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(help_text="Short summary for listings")),
                ("content", models.TextField(help_text="Main content body")),
                (
                    "content_format",
                    models.CharField(
                        choices=[("markdown", "Markdown"), ("rich_text", "Rich Text")],
                        default="markdown",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("published", "Published"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version_number", models.IntegerField(default=1, help_text="Current version number")),
                ("tags", models.JSONField(blank=True, default=list, help_text="Tags for search and filtering")),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Category (SOP Library, Training, KPI Definitions, etc.)", max_length=50
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("all_staff", "All Staff"),
                            ("manager_plus", "Manager+"),
                            ("admin_only", "Admin Only"),
                        ],
                        default="all_staff",
                        help_text="Minimum role required to view",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, help_text="When this version was published", null=True),
                ),
                (
                    "deprecated_at",
                    models.DateTimeField(blank=True, help_text="When this item was deprecated", null=True),
                ),
                (
                    "deprecation_reason",
                    models.TextField(blank=True, help_text="Required when deprecating (docs/35 section 3)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_knowledge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this knowledge item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to="firm.firm",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Staff user who owns this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_knowledge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_items",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "decision",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_reviews", to="firm.firm"
                    ),
                ),
                (
                    "knowledge_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="knowledge.knowledgeitem",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_knowledge_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_reviews",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="reviewers",
            field=models.ManyToManyField(
                help_text="Staff users who can review this item",
                related_name="reviewed_knowledge_items",
                through="knowledge.KnowledgeReview",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_knowledge_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("template", "Delivery Template"),
                            ("metric", "Metric Definition"),
                            ("external", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_url", models.URLField(blank=True, help_text="External link (allowed list policy)")),
                (
                    "description",
                    models.CharField(blank=True, help_text="Optional description of attachment", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_knowledge_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to delivery template",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery.deliverytemplate",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to governed document",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_attachments",
                        to="firm.firm",
                    ),
                ),
                (
                    "knowledge_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="knowledge.knowledgeitem",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.IntegerField()),
                ("content_snapshot", models.TextField(help_text="Content at time of version")),
                (
                    "content_format",
                    models.CharField(choices=[("markdown", "Markdown"), ("rich_text", "Rich Text")], max_length=20),
                ),
                ("change_notes", models.TextField(blank=True, help_text="What changed in this version")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_knowledge_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_versions", to="firm.firm"
                    ),
                ),
                (
                    "knowledge_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="knowledge.knowledgeitem",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_versions",
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(fields=["firm", "knowledge_item"], name="knowledge_ver_fir_kno_idx"),
                    models.Index(fields=["knowledge_item", "-version_number"], name="knowledge_kno_ver_idx"),
                ],
                "unique_together": {("knowledge_item", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="knowledgereview",
            index=models.Index(fields=["firm", "knowledge_item"], name="knowledge_rev_fir_kno_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgereview",
            index=models.Index(fields=["reviewer", "decision"], name="knowledge_rev_dec_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgereview",
            unique_together={("knowledge_item", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(fields=["firm", "status"], name="knowledge_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(fields=["firm", "type"], name="knowledge_fir_typ_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(fields=["firm", "owner"], name="knowledge_fir_own_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(fields=["status", "published_at"], name="knowledge_sta_pub_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeitem",
            unique_together={("firm", "title", "version_number")},
        ),
        migrations.AddIndex(
            model_name="knowledgeattachment",
            index=models.Index(fields=["firm", "knowledge_item"], name="knowledge_att_fir_kno_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgeattachment",
            index=models.Index(fields=["attachment_type"], name="knowledge_att_idx"),
        ),
    ]
