# Generated by Django 4.2.17 on 2026-01-01 04:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modules.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0008_contact_engagementline_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0005_intake_forms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("note", "Note"),
                            ("task", "Task"),
                            ("proposal_sent", "Proposal Sent"),
                            ("contract_signed", "Contract Signed"),
                            ("follow_up", "Follow-up"),
                            ("other", "Other"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="outbound",
                        help_text="Direction of communication",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(help_text="Activity subject/title", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Detailed notes about the activity")),
                ("activity_date", models.DateTimeField(help_text="When the activity occurred")),
                (
                    "duration_minutes",
                    models.IntegerField(blank=True, help_text="Duration in minutes (for calls/meetings)", null=True),
                ),
                (
                    "requires_follow_up",
                    models.BooleanField(default=False, help_text="Whether this activity requires follow-up"),
                ),
                ("follow_up_date", models.DateField(blank=True, help_text="When to follow up", null=True)),
                (
                    "follow_up_completed",
                    models.BooleanField(default=False, help_text="Whether follow-up was completed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Activities",
                "db_table": "crm_activities",
                "ordering": ["-activity_date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="Unique product code/SKU", max_length=100)),
                ("name", models.CharField(help_text="Product name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Product description")),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("product", "Product"),
                            ("subscription", "Subscription"),
                            ("bundle", "Bundle"),
                        ],
                        default="service",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price before configuration",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", help_text="Currency code (ISO 4217)", max_length=3)),
                (
                    "is_configurable",
                    models.BooleanField(default=False, help_text="Whether this product has configurable options"),
                ),
                (
                    "configuration_schema",
                    models.JSONField(
                        blank=True, default=dict, help_text="JSON schema defining configuration rules and dependencies"
                    ),
                ),
                ("category", models.CharField(blank=True, help_text="Product category", max_length=100)),
                ("tags", models.JSONField(blank=True, default=list, help_text="Product tags for filtering")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crm_product",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "configuration_name",
                    models.CharField(blank=True, help_text="Optional name for this configuration", max_length=255),
                ),
                (
                    "selected_options",
                    models.JSONField(default=dict, help_text="Selected options: {option_code: value}"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Base price at time of configuration", max_digits=12
                    ),
                ),
                (
                    "configuration_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Total price after applying configuration", max_digits=12
                    ),
                ),
                (
                    "price_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed price breakdown: {base, options, discounts, total}",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount percentage applied to configuration",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Calculated discount amount", max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("validated", "Validated"), ("quoted", "Quoted")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True, default=list, help_text="Validation errors if configuration is invalid"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crm_product_configuration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="Option code", max_length=100)),
                ("label", models.CharField(help_text="Display label", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Option description")),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("single_select", "Single Select"),
                            ("multi_select", "Multi Select"),
                            ("text", "Text Input"),
                            ("number", "Number Input"),
                            ("boolean", "Boolean"),
                        ],
                        default="single_select",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False, help_text="Whether this option is required")),
                ("display_order", models.IntegerField(default=0, help_text="Display order in UI")),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available values for select options: [{value, label, price_modifier}]",
                    ),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed price modifier (added to base price)",
                        max_digits=12,
                    ),
                ),
                (
                    "price_multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Price multiplier (applied to base price)",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                (
                    "dependency_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rules defining when this option is available based on other options",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crm_product_option",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ScoreAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("points", models.IntegerField(help_text="Points added or subtracted")),
                ("reason", models.CharField(help_text="Reason for adjustment", max_length=500)),
                (
                    "trigger_event",
                    models.CharField(blank=True, help_text="Event that triggered this adjustment", max_length=50),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Event data (e.g., email_id, page_url, form_id)"
                    ),
                ),
                (
                    "decays_at",
                    models.DateTimeField(blank=True, help_text="When these points will decay to 0", null=True),
                ),
                ("is_decayed", models.BooleanField(default=False, help_text="Whether these points have decayed")),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "score_adjustments",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Descriptive name for this rule", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Detailed description of what this rule does")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("demographic", "Demographic"),
                            ("behavioral", "Behavioral"),
                            ("engagement", "Engagement"),
                            ("firmographic", "Firmographic"),
                            ("custom", "Custom"),
                        ],
                        help_text="Type of scoring rule",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("email_opened", "Email Opened"),
                            ("email_clicked", "Email Link Clicked"),
                            ("form_submitted", "Form Submitted"),
                            ("page_visited", "Page Visited"),
                            ("document_downloaded", "Document Downloaded"),
                            ("meeting_booked", "Meeting Booked"),
                            ("meeting_attended", "Meeting Attended"),
                            ("proposal_viewed", "Proposal Viewed"),
                            ("reply_received", "Reply to Email Received"),
                            ("phone_answered", "Phone Call Answered"),
                            ("referral_made", "Referral Made"),
                            ("social_engagement", "Social Media Engagement"),
                            ("job_title_match", "Job Title Matches Criteria"),
                            ("company_size_match", "Company Size in Range"),
                            ("industry_match", "Industry Matches"),
                            ("location_match", "Location Matches"),
                            ("budget_range_match", "Budget in Range"),
                            ("custom_field_match", "Custom Field Matches"),
                            ("tag_added", "Tag Added"),
                            ("status_changed", "Status Changed"),
                        ],
                        help_text="Event that triggers this rule",
                        max_length=50,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Conditions that must be met (JSON object with field: value pairs)"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Points to add (positive) or subtract (negative) when rule matches",
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_applications",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum times this rule can be applied to same lead (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "decay_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Days after which points from this rule decay to 0 (null = no decay)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this rule is active")),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="Rule priority for execution order (higher = earlier)"),
                ),
                (
                    "times_applied",
                    models.IntegerField(default=0, help_text="Total number of times this rule has been applied"),
                ),
                (
                    "last_applied_at",
                    models.DateTimeField(blank=True, help_text="When this rule was last applied", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scoring_rules",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="account",
            name="crm_account_firm_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="accountcontact",
            name="crm_accountcontact_account_email_unique",
        ),
        migrations.RemoveConstraint(
            model_name="accountrelationship",
            name="crm_accountrelationship_from_to_type_unique",
        ),
        migrations.RemoveIndex(
            model_name="campaign",
            name="crm_campaign_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="contract",
            name="crm_contract_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="contract",
            name="crm_contract_end_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="crm_lead_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="crm_lead_assigned_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="crm_lead_source_idx",
        ),
        migrations.RemoveIndex(
            model_name="proposal",
            name="crm_proposal_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="proposal",
            name="crm_proposal_prospect_idx",
        ),
        migrations.RemoveIndex(
            model_name="proposal",
            name="crm_proposal_expires_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="crm_prospec_firm_id_0d42e6_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="crm_prospect_contact_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="crm_prospect_stage_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_cam_idx",
            old_name="crm_leads_campaig_c0672e_idx",
        ),
        migrations.AddField(
            model_name="prospect",
            name="consent_source",
            field=models.CharField(
                blank=True,
                help_text="Source of consent (e.g., 'lead_form', 'email_campaign', 'website')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="consent_timestamp",
            field=models.DateTimeField(blank=True, help_text="When consent was given (GDPR requirement)", null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="marketing_opt_in",
            field=models.BooleanField(
                default=False, help_text="Has the prospect opted in to receive marketing communications?"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="website",
            field=models.URLField(blank=True, validators=[modules.core.validators.validate_safe_url]),
        ),
        migrations.AlterField(
            model_name="lead",
            name="website",
            field=models.URLField(blank=True, validators=[modules.core.validators.validate_safe_url]),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="stage",
            field=models.CharField(
                choices=[
                    ("discovery", "Discovery"),
                    ("needs_analysis", "Needs Analysis"),
                    ("proposal", "Proposal Sent"),
                    ("negotiation", "Negotiation"),
                    ("won", "Won - Converting to Client"),
                    ("lost", "Lost"),
                ],
                default="discovery",
                help_text="Current pipeline stage",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="website",
            field=models.URLField(blank=True, validators=[modules.core.validators.validate_safe_url]),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("firm", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="accountcontact",
            unique_together={("account", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="accountrelationship",
            unique_together={("from_account", "to_account", "relationship_type")},
        ),
        migrations.AlterUniqueTogether(
            name="prospect",
            unique_together={("firm", "company_name")},
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(fields=["firm", "stage"], name="crm_prospec_firm_id_8b1c2f_idx"),
        ),
        migrations.AddField(
            model_name="scoringrule",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this rule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_scoring_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scoringrule",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm this rule belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_rules",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="scoreadjustment",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who applied this adjustment (null if automated)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="score_adjustments_applied",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scoreadjustment",
            name="lead",
            field=models.ForeignKey(
                help_text="Lead this adjustment applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score_adjustments",
                to="crm.lead",
            ),
        ),
        migrations.AddField(
            model_name="scoreadjustment",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Rule that created this adjustment (null if manual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adjustments",
                to="crm.scoringrule",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                help_text="Product this option belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="crm.product",
            ),
        ),
        migrations.AddField(
            model_name="productconfiguration",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_configurations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productconfiguration",
            name="product",
            field=models.ForeignKey(
                help_text="Product being configured",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="crm.product",
            ),
        ),
        migrations.AddField(
            model_name="productconfiguration",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                help_text="Quote created from this configuration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_configurations",
                to="pricing.quote",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this product belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cpq_products",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Campaign this activity is part of",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="crm.campaign",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client this activity is associated with",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_activities",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who logged this activity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm (workspace) this activity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Lead this activity is associated with",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="crm.lead",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                help_text="Proposal this activity is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="crm.proposal",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="prospect",
            field=models.ForeignKey(
                blank=True,
                help_text="Prospect this activity is associated with",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="crm.prospect",
            ),
        ),
        migrations.AddIndex(
            model_name="scoringrule",
            index=models.Index(fields=["firm", "is_active"], name="scoring_rul_firm_id_8e807e_idx"),
        ),
        migrations.AddIndex(
            model_name="scoringrule",
            index=models.Index(fields=["firm", "rule_type"], name="scoring_rul_firm_id_daf888_idx"),
        ),
        migrations.AddIndex(
            model_name="scoringrule",
            index=models.Index(fields=["trigger"], name="scoring_rul_trigger_ec0184_idx"),
        ),
        migrations.AddIndex(
            model_name="scoringrule",
            index=models.Index(fields=["-priority"], name="scoring_rul_priorit_84849b_idx"),
        ),
        migrations.AddIndex(
            model_name="scoreadjustment",
            index=models.Index(fields=["lead", "-applied_at"], name="score_adjus_lead_id_f4f06a_idx"),
        ),
        migrations.AddIndex(
            model_name="scoreadjustment",
            index=models.Index(fields=["rule", "-applied_at"], name="score_adjus_rule_id_8c5dee_idx"),
        ),
        migrations.AddIndex(
            model_name="scoreadjustment",
            index=models.Index(fields=["trigger_event"], name="score_adjus_trigger_c22978_idx"),
        ),
        migrations.AddIndex(
            model_name="scoreadjustment",
            index=models.Index(fields=["decays_at", "is_decayed"], name="score_adjus_decays__ce5dd9_idx"),
        ),
        migrations.AddIndex(
            model_name="productoption",
            index=models.Index(fields=["product", "display_order"], name="crm_prod_opt_prod_ord_idx"),
        ),
        migrations.AddIndex(
            model_name="productoption",
            index=models.Index(fields=["product", "code"], name="crm_prod_opt_prod_code_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productoption",
            unique_together={("product", "code")},
        ),
        migrations.AddIndex(
            model_name="productconfiguration",
            index=models.Index(fields=["product", "-created_at"], name="crm_prod_cfg_prod_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="productconfiguration",
            index=models.Index(fields=["product", "status"], name="crm_prod_cfg_prod_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="productconfiguration",
            index=models.Index(fields=["quote"], name="crm_prod_cfg_quote_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["firm", "status"], name="crm_prod_firm_status_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["firm", "code"], name="crm_prod_firm_code_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["firm", "product_type"], name="crm_prod_firm_type_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("firm", "code")},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["firm", "-activity_date"], name="crm_activit_firm_id_80f8ac_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["firm", "activity_type"], name="crm_activit_firm_id_1604cc_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["lead", "-activity_date"], name="crm_lea_act_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["prospect", "-activity_date"], name="crm_pro_act_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["client", "-activity_date"], name="crm_cli_act_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["created_by", "-activity_date"], name="crm_cre_act_idx"),
        ),
    ]
