# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0008_contact_engagementline_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendar", "0003_sync_retry_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingPoll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Meeting poll title", max_length=500)),
                ("description", models.TextField(blank=True, help_text="Meeting description")),
                ("duration_minutes", models.IntegerField(help_text="Meeting duration in minutes")),
                (
                    "location_mode",
                    models.CharField(
                        choices=[
                            ("video", "Video Call"),
                            ("phone", "Phone Call"),
                            ("in_person", "In Person"),
                            ("custom", "Custom"),
                        ],
                        default="video",
                        help_text="How the meeting will be conducted",
                        max_length=20,
                    ),
                ),
                ("location_details", models.TextField(blank=True, help_text="Additional location info")),
                ("invitees", models.JSONField(default=list, help_text="List of invitee emails or user IDs")),
                (
                    "proposed_slots",
                    models.JSONField(
                        default=list, help_text="List of proposed time slots {start_time, end_time, timezone}"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("scheduled", "Meeting Scheduled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        help_text="Poll status",
                        max_length=20,
                    ),
                ),
                (
                    "voting_deadline",
                    models.DateTimeField(blank=True, help_text="When voting closes (optional)", null=True),
                ),
                (
                    "selected_slot_index",
                    models.IntegerField(
                        blank=True, help_text="Index of the selected slot from proposed_slots", null=True
                    ),
                ),
                (
                    "allow_maybe_votes",
                    models.BooleanField(default=True, help_text="Allow 'maybe' votes in addition to yes/no"),
                ),
                (
                    "require_all_invitees",
                    models.BooleanField(default=False, help_text="Require all invitees to respond before scheduling"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "calendar_meeting_polls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingPollVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("voter_email", models.EmailField(help_text="Email of voter (for external invitees)", max_length=254)),
                ("voter_name", models.CharField(help_text="Name of voter", max_length=255)),
                ("responses", models.JSONField(default=list, help_text="Array of responses for each proposed slot")),
                ("notes", models.TextField(blank=True, help_text="Optional notes from voter")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "calendar_meeting_poll_votes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingWorkflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Workflow name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Workflow description")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("appointment_created", "Appointment Created"),
                            ("appointment_confirmed", "Appointment Confirmed"),
                            ("appointment_completed", "Appointment Completed"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                        ],
                        help_text="When to trigger this workflow",
                        max_length=30,
                    ),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Delay before executing action (minutes, can be negative for 'before' actions)",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_email", "Send Email"),
                            ("send_sms", "Send SMS"),
                            ("create_task", "Create Task"),
                            ("send_survey", "Send Survey"),
                            ("update_crm", "Update CRM"),
                        ],
                        help_text="Type of action to perform",
                        max_length=20,
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        default=dict, help_text="Action configuration (email template, SMS text, survey ID, etc.)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused"), ("archived", "Archived")],
                        default="active",
                        help_text="Workflow status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "calendar_meeting_workflows",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MeetingWorkflowExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Execution status",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(help_text="When this workflow should execute")),
                ("executed_at", models.DateTimeField(blank=True, help_text="When workflow was executed", null=True)),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Execution result data (email sent, task created, etc.)"
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if execution failed")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "calendar_workflow_executions",
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="OAuthAuthorizationCode",
            fields=[
                ("code_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "state_token",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="OAuth state parameter for CSRF protection", unique=True
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google Calendar"),
                            ("microsoft", "Microsoft Outlook/Office 365"),
                            ("apple", "Apple Calendar (iCloud)"),
                        ],
                        help_text="Calendar provider",
                        max_length=20,
                    ),
                ),
                (
                    "authorization_code",
                    models.TextField(blank=True, help_text="OAuth authorization code from provider"),
                ),
                ("redirect_uri", models.URLField(help_text="Redirect URI used in OAuth flow", max_length=512)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Exchange"),
                            ("exchanged", "Exchanged for Tokens"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Authorization code state",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="When this code expires")),
                ("error_message", models.TextField(blank=True, help_text="Error message if exchange failed")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exchanged_at", models.DateTimeField(blank=True, help_text="When code was exchanged", null=True)),
            ],
            options={
                "db_table": "calendar_oauth_authorization_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OAuthConnection",
            fields=[
                ("connection_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google Calendar"),
                            ("microsoft", "Microsoft Outlook/Office 365"),
                            ("apple", "Apple Calendar (iCloud)"),
                        ],
                        help_text="Calendar provider",
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField(blank=True, help_text="Encrypted OAuth access token")),
                ("refresh_token", models.TextField(blank=True, help_text="Encrypted OAuth refresh token")),
                (
                    "token_expires_at",
                    models.DateTimeField(blank=True, help_text="When access token expires", null=True),
                ),
                ("scopes", models.JSONField(blank=True, default=list, help_text="OAuth scopes granted")),
                (
                    "provider_user_id",
                    models.CharField(
                        blank=True, help_text="Provider user ID (Google: email, Microsoft: user ID)", max_length=255
                    ),
                ),
                (
                    "provider_email",
                    models.EmailField(blank=True, help_text="Email address of connected calendar", max_length=254),
                ),
                (
                    "provider_metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional provider-specific metadata"),
                ),
                ("sync_enabled", models.BooleanField(default=True, help_text="Whether automatic sync is enabled")),
                (
                    "sync_window_days",
                    models.IntegerField(default=30, help_text="Number of days to sync (past and future)"),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful sync timestamp", null=True),
                ),
                (
                    "last_sync_cursor",
                    models.TextField(blank=True, help_text="Sync cursor/token from provider (for delta sync)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired (Token Refresh Needed)"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="active",
                        help_text="Connection status",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="Last error message if status=error")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "calendar_oauth_connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="calendar_ap_externa_1d5f9c_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="calendar_fir_sta_sta_idx",
            old_name="calendar_ap_firm_id_9b2e5a_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="calendar_fir_acc_idx",
            old_name="calendar_ap_firm_id_4c7d1f_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="calendar_app_fir_sta_idx",
            old_name="calendar_ap_firm_id_6e3a8b_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="calendar_cal_ext_idx",
            old_name="calendar_ap_calenda_3f8a2d_idx",
        ),
        migrations.RenameIndex(
            model_name="appointmentstatushistory",
            new_name="calendar_app_cha_idx",
            old_name="calendar_ap_appoint_7a4e2d_idx",
        ),
        migrations.RenameIndex(
            model_name="appointmenttype",
            new_name="calendar_apt_fir_sta_idx",
            old_name="calendar_ap_firm_id_3a8e2d_idx",
        ),
        migrations.RenameIndex(
            model_name="availabilityprofile",
            new_name="calendar_fir_own_own_idx",
            old_name="calendar_av_firm_id_7d4c1a_idx",
        ),
        migrations.RenameIndex(
            model_name="bookinglink",
            new_name="calendar_bkl_fir_sta_idx",
            old_name="calendar_bo_firm_id_5e9b2f_idx",
        ),
        migrations.RenameIndex(
            model_name="bookinglink",
            new_name="calendar_slu_idx",
            old_name="calendar_bo_slug_8a3d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="bookinglink",
            new_name="calendar_tok_idx",
            old_name="calendar_bo_token_2f6c1b_idx",
        ),
        migrations.RenameIndex(
            model_name="calendarconnection",
            new_name="calendar_fir_own_sta_idx",
            old_name="calendar_ca_firm_id_6d2e9a_idx",
        ),
        migrations.RenameIndex(
            model_name="calendarconnection",
            new_name="calendar_pro_sta_idx",
            old_name="calendar_ca_provide_8b3f1c_idx",
        ),
        migrations.RenameIndex(
            model_name="syncattemptlog",
            new_name="calendar_fir_con_sta_idx",
            old_name="calendar_sy_firm_id_4a7e2b_idx",
        ),
        migrations.RenameIndex(
            model_name="syncattemptlog",
            new_name="calendar_sta_err_idx",
            old_name="calendar_sy_status_9c2d5e_idx",
        ),
        migrations.RenameIndex(
            model_name="syncattemptlog",
            new_name="calendar_cor_idx",
            old_name="calendar_sy_correla_7f3a8d_idx",
        ),
        migrations.RenameIndex(
            model_name="syncattemptlog",
            new_name="calendar_nex_idx",
            old_name="calendar_sy_next_re_idx",
        ),
        migrations.RenameIndex(
            model_name="syncattemptlog",
            new_name="calendar_max_idx",
            old_name="calendar_sy_max_ret_idx",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Client account for this appointment (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Contact for this appointment (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="clients.contact",
            ),
        ),
        migrations.AlterField(
            model_name="bookinglink",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to specific client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_links",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="bookinglink",
            name="engagement",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to specific engagement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_links",
                to="clients.clientengagement",
            ),
        ),
        migrations.AddField(
            model_name="oauthconnection",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm this connection belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_calendar_connections",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="oauthconnection",
            name="user",
            field=models.ForeignKey(
                help_text="Staff user who owns this connection",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_oauth_connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="oauthauthorizationcode",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                help_text="Resulting connection (after exchange)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorization_codes",
                to="calendar.oauthconnection",
            ),
        ),
        migrations.AddField(
            model_name="oauthauthorizationcode",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm for this authorization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_authorization_codes",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="oauthauthorizationcode",
            name="user",
            field=models.ForeignKey(
                help_text="User initiating OAuth flow",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_authorization_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetingworkflowexecution",
            name="appointment",
            field=models.ForeignKey(
                help_text="Appointment that triggered this workflow",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_executions",
                to="calendar.appointment",
            ),
        ),
        migrations.AddField(
            model_name="meetingworkflowexecution",
            name="workflow",
            field=models.ForeignKey(
                help_text="Workflow being executed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="calendar.meetingworkflow",
            ),
        ),
        migrations.AddField(
            model_name="meetingworkflow",
            name="appointment_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Apply workflow to this appointment type (null = all types)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="calendar.appointmenttype",
            ),
        ),
        migrations.AddField(
            model_name="meetingworkflow",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetingworkflow",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm this workflow belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_workflows",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="meetingpollvote",
            name="poll",
            field=models.ForeignKey(
                help_text="Poll this vote belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="calendar.meetingpoll",
            ),
        ),
        migrations.AddField(
            model_name="meetingpollvote",
            name="voter_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who voted (if authenticated)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetingpoll",
            name="created_by",
            field=models.ForeignKey(
                help_text="Staff member who created this poll",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_polls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetingpoll",
            name="firm",
            field=models.ForeignKey(
                help_text="Firm this poll belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_polls",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="meetingpoll",
            name="scheduled_appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Appointment created from this poll",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_poll",
                to="calendar.appointment",
            ),
        ),
        migrations.AddIndex(
            model_name="oauthconnection",
            index=models.Index(fields=["firm", "user", "provider"], name="calendar_oa_firm_id_cda0bc_idx"),
        ),
        migrations.AddIndex(
            model_name="oauthconnection",
            index=models.Index(fields=["firm", "status"], name="calendar_oa_firm_id_b12643_idx"),
        ),
        migrations.AddIndex(
            model_name="oauthconnection",
            index=models.Index(fields=["provider", "status"], name="calendar_oa_provide_738f7d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="oauthconnection",
            unique_together={("firm", "user", "provider")},
        ),
        migrations.AddIndex(
            model_name="oauthauthorizationcode",
            index=models.Index(fields=["state_token"], name="calendar_oa_state_t_ad803e_idx"),
        ),
        migrations.AddIndex(
            model_name="oauthauthorizationcode",
            index=models.Index(fields=["firm", "user", "state"], name="calendar_oa_firm_id_82a0f4_idx"),
        ),
        migrations.AddIndex(
            model_name="oauthauthorizationcode",
            index=models.Index(fields=["expires_at"], name="calendar_oa_expires_2ae79f_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingworkflowexecution",
            index=models.Index(fields=["workflow", "status"], name="calendar_wor_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingworkflowexecution",
            index=models.Index(fields=["appointment", "status"], name="calendar_exe_app_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingworkflowexecution",
            index=models.Index(fields=["status", "scheduled_for"], name="calendar_sta_sch_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingworkflow",
            index=models.Index(fields=["firm", "status"], name="calendar_wfl_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingworkflow",
            index=models.Index(fields=["firm", "trigger"], name="calendar_fir_tri_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingworkflow",
            index=models.Index(fields=["appointment_type", "status"], name="calendar_wfl_app_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingpollvote",
            index=models.Index(fields=["poll", "voter_email"], name="calendar_pol_vot_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingpollvote",
            index=models.Index(fields=["voter_user", "-created_at"], name="calendar_vot_cre_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="meetingpollvote",
            unique_together={("poll", "voter_email")},
        ),
        migrations.AddIndex(
            model_name="meetingpoll",
            index=models.Index(fields=["firm", "status"], name="calendar_pol_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingpoll",
            index=models.Index(fields=["firm", "-created_at"], name="calendar_fir_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingpoll",
            index=models.Index(fields=["created_by", "status"], name="calendar_cre_sta_idx"),
        ),
    ]
