# Generated by Django 4.2.8 on 2025-12-24 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('firm', '0002_break_glass_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='platform_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('platform_role', models.CharField(blank=True, choices=[(None, 'None (Firm User)'), ('operator', 'Platform Operator'), ('break_glass', 'Break-Glass Operator')], default=None, help_text='Platform-level role. None = regular firm user. Operator = metadata-only platform access. Break-Glass = can activate break-glass sessions for content access.', max_length=20, null=True)),
                ('timezone', models.CharField(default='UTC', help_text="User's preferred timezone", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'firm_user_profile',
                'indexes': [models.Index(fields=['platform_role'], name='firm_user_p_platfor_a4d546_idx')],
            },
        ),
    ]
