# Generated by Django 4.2.8 on 2025-12-25 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0003_platform_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUTH", "Authentication & Authorization"),
                            ("PERMISSIONS", "Permission Changes"),
                            ("BREAK_GLASS", "Break-Glass Access"),
                            ("BILLING_METADATA", "Billing Metadata"),
                            ("PURGE", "Content Purge"),
                            ("CONFIG", "Configuration Changes"),
                            ("DATA_ACCESS", "Data Access"),
                            ("SYSTEM", "System Events"),
                        ],
                        db_index=True,
                        help_text="Event category for filtering and review",
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Specific action taken (e.g., 'login_failed', 'purge_document', 'break_glass_activated')",
                        max_length=255,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informational"),
                            ("WARNING", "Warning - Requires Review"),
                            ("CRITICAL", "Critical - Immediate Review Required"),
                        ],
                        db_index=True,
                        default="INFO",
                        help_text="Event severity for prioritization",
                        max_length=20,
                    ),
                ),
                (
                    "actor_email",
                    models.EmailField(
                        blank=True, help_text="Email at time of action (preserved even if user deleted)", max_length=254
                    ),
                ),
                ("actor_role", models.CharField(blank=True, help_text="User's role at time of action", max_length=50)),
                (
                    "target_model",
                    models.CharField(
                        blank=True, help_text="Model name of target object (e.g., 'Client', 'Document')", max_length=100
                    ),
                ),
                ("target_id", models.CharField(blank=True, help_text="ID of target object", max_length=255)),
                (
                    "target_repr",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable representation of target (no sensitive data)",
                        max_length=500,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, help_text="When the event occurred"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for action (required for break-glass, purge, etc.)"),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True, help_text="Result of action (e.g., 'success', 'denied', 'failed')", max_length=50
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context (metadata only, never customer content)"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, help_text="IP address of request", null=True)),
                ("user_agent", models.CharField(blank=True, help_text="User agent string", max_length=500)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, help_text="Request ID for correlation", max_length=100),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this event was reviewed (for anomaly detection)", null=True
                    ),
                ),
                ("review_notes", models.TextField(blank=True, help_text="Notes from review")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for system events)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events_as_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (tenant) this event belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="firm.firm",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "firm_audit_events",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("review_audit_events", "Can review audit events"),
                    ("export_audit_events", "Can export audit events"),
                ],
                "indexes": [
                    models.Index(fields=["firm", "category", "-timestamp"], name="firm_audit__firm_id_22bf3a_idx"),
                    models.Index(fields=["firm", "actor", "-timestamp"], name="firm_audit__firm_id_349867_idx"),
                    models.Index(fields=["category", "severity", "-timestamp"], name="firm_audit__categor_39c738_idx"),
                    models.Index(fields=["firm", "action", "-timestamp"], name="firm_audit__firm_id_08a19b_idx"),
                ],
            },
        ),
    ]
