# Generated by Django 4.2.8 on 2025-12-24 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firm', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AUTH', 'Authentication & Authorization'), ('PERMISSIONS', 'Permission Changes'), ('BREAK_GLASS', 'Break-Glass Access'), ('BILLING_METADATA', 'Billing Metadata Access'), ('PURGE', 'Content Purge'), ('CONFIG', 'Configuration Change')], db_index=True, help_text='Event category for filtering and review', max_length=50)),
                ('action', models.CharField(db_index=True, help_text="Specific action taken (e.g., 'break_glass_activated')", max_length=100)),
                ('actor_username', models.CharField(help_text='Actor username (denormalized for immutability)', max_length=150)),
                ('actor_email', models.EmailField(blank=True, help_text='Actor email (denormalized for immutability)', max_length=254)),
                ('target_model', models.CharField(blank=True, help_text="Target model (e.g., 'Document', 'BreakGlassSession')", max_length=100)),
                ('target_id', models.CharField(blank=True, help_text='Target object ID', max_length=100)),
                ('target_description', models.CharField(blank=True, help_text='Human-readable target description', max_length=255)),
                ('reason', models.TextField(blank=True, help_text='Reason for action (required for break-glass)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (IP, user agent, etc.) - never contains content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(blank=True, help_text='Firm context (null for platform-wide events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='firm.firm')),
            ],
            options={
                'db_table': 'firm_audit_event',
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_events', 'Can view audit events')],
                'indexes': [models.Index(fields=['firm', 'category', '-timestamp'], name='firm_audit__firm_id_fd3310_idx'), models.Index(fields=['actor', '-timestamp'], name='firm_audit__actor_i_d2ea67_idx'), models.Index(fields=['category', 'action', '-timestamp'], name='firm_audit__categor_888829_idx')],
            },
        ),
    ]
