# Generated by Django for DOC-19.1 provisioning workflow

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firm', '0006_firm_offboarding_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total provisioning duration in seconds', null=True)),
                ('correlation_id', models.CharField(db_index=True, help_text='Correlation ID for request tracing', max_length=255)),
                ('provisioning_config', models.JSONField(default=dict, help_text='Configuration used for provisioning (firm details, admin user, etc.)')),
                ('steps_completed', models.JSONField(default=list, help_text='List of provisioning steps successfully completed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if provisioning failed')),
                ('error_step', models.CharField(blank=True, help_text='Step where provisioning failed', max_length=100)),
                ('metadata', models.JSONField(default=dict, help_text='Additional provisioning metadata (created resources, etc.)')),
                ('firm', models.ForeignKey(help_text='Firm that was provisioned (null if provisioning failed early)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_logs', to='firm.firm')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated provisioning (platform operator)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firm_provisioning_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='provisioninglog',
            index=models.Index(fields=['status'], name='idx_provisioninglog__status'),
        ),
        migrations.AddIndex(
            model_name='provisioninglog',
            index=models.Index(fields=['correlation_id'], name='idx_provisioninglog__correlation_id'),
        ),
        migrations.AddIndex(
            model_name='provisioninglog',
            index=models.Index(fields=['-started_at'], name='idx_provisioninglog__started_at'),
        ),
    ]
