# Generated by Django 4.2.8 on 2025-12-25 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0004_auditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurgedContent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("message", "Message"),
                            ("comment", "Comment"),
                            ("note", "Note"),
                            ("document_version", "Document Version"),
                            ("invoice_line_item", "Invoice Line Item"),
                        ],
                        db_index=True,
                        help_text="Type of content that was purged",
                        max_length=50,
                    ),
                ),
                (
                    "original_model",
                    models.CharField(help_text="Django model name (e.g., 'documents.Document')", max_length=100),
                ),
                (
                    "original_id",
                    models.CharField(db_index=True, help_text="ID of original object before purge", max_length=255),
                ),
                ("created_at", models.DateTimeField(help_text="When original content was created")),
                (
                    "file_size_bytes",
                    models.BigIntegerField(blank=True, help_text="Size of purged file (metadata only)", null=True),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, help_text="MIME type of purged file (metadata only)", max_length=255),
                ),
                (
                    "purged_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, help_text="When content was purged"
                    ),
                ),
                (
                    "purge_reason_category",
                    models.CharField(
                        choices=[
                            ("gdpr_erasure", "GDPR Right to Erasure (Article 17)"),
                            ("ccpa_deletion", "CCPA Deletion Request"),
                            ("legal_hold_expired", "Legal Hold Expired"),
                            ("firm_offboarding", "Firm Offboarding/Deletion"),
                            ("court_order", "Court Order"),
                            ("other_legal", "Other Legal Requirement"),
                        ],
                        help_text="Legal basis for purge",
                        max_length=50,
                    ),
                ),
                (
                    "purge_reason_detail",
                    models.TextField(help_text="Detailed explanation for purge (e.g., ticket number, legal case)"),
                ),
                (
                    "legal_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to legal documentation (case number, request ID, etc.)",
                        max_length=500,
                    ),
                ),
                (
                    "confirmation_token",
                    models.CharField(
                        blank=True, help_text="Confirmation token from Master Admin approval", max_length=100
                    ),
                ),
                (
                    "audit_event_id",
                    models.BigIntegerField(blank=True, help_text="Link to audit event for this purge", null=True),
                ),
                (
                    "was_signed",
                    models.BooleanField(default=False, help_text="Whether content had a signature before purge"),
                ),
                (
                    "signature_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Preserved signature metadata (who, when, version hash - NO CONTENT)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Who created the original content",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purged_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm that owned the purged content",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purged_content",
                        to="firm.firm",
                    ),
                ),
                (
                    "purged_by",
                    models.ForeignKey(
                        help_text="Master Admin who authorized purge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purged_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_purged_content",
                "ordering": ["-purged_at"],
                "permissions": [("can_purge_content", "Can purge customer content (Master Admin only)")],
                "indexes": [
                    models.Index(fields=["firm", "content_type", "-purged_at"], name="core_purged_firm_id_b02d65_idx"),
                    models.Index(fields=["original_model", "original_id"], name="core_purged_origina_03503c_idx"),
                    models.Index(fields=["purged_by", "-purged_at"], name="core_purged_purged__3d3006_idx"),
                ],
            },
        ),
    ]
