# Generated by manual migration for SEC-1 idempotency keys

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esignature", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Idempotency key for this webhook event",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
