# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calendar", "0004_meetingpoll_meetingpollvote_meetingworkflow_and_more"),
        ("documents", "0004_document_classification_document_deprecated_at_and_more"),
        ("clients", "0008_contact_engagementline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingProcess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Process name (defaults to template name)", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("waiting_client", "Waiting on Client"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        help_text="Current process status",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, help_text="When onboarding started", null=True)),
                (
                    "target_completion_date",
                    models.DateField(blank=True, help_text="Target date for completion", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When onboarding was completed", null=True),
                ),
                ("total_tasks", models.IntegerField(default=0, help_text="Total number of tasks in this onboarding")),
                ("completed_tasks", models.IntegerField(default=0, help_text="Number of completed tasks")),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0, help_text="Completion percentage", max_digits=5),
                ),
                (
                    "kickoff_scheduled",
                    models.BooleanField(default=False, help_text="Has kick-off meeting been scheduled?"),
                ),
                (
                    "kickoff_completed",
                    models.BooleanField(default=False, help_text="Has kick-off meeting been completed?"),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                ("blockers", models.TextField(blank=True, help_text="Current blockers or issues")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member responsible for this onboarding",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_onboardings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client being onboarded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_processes",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_onboarding_processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this onboarding process belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_processes",
                        to="firm.firm",
                    ),
                ),
                (
                    "kickoff_appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kick-off meeting appointment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_kickoffs",
                        to="calendar.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_processes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Template name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Template description")),
                (
                    "service_type",
                    models.CharField(blank=True, help_text="Type of service this onboarding is for", max_length=100),
                ),
                ("steps", models.JSONField(default=list, help_text="Onboarding steps and tasks definition (JSON)")),
                (
                    "estimated_duration_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated duration in days to complete onboarding",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")],
                        default="draft",
                        help_text="Template status",
                        max_length=20,
                    ),
                ),
                ("times_used", models.IntegerField(default=0, help_text="Number of times this template has been used")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_onboarding_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_templates",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Task name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Task description")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("information", "Collect Information"),
                            ("document", "Upload Document"),
                            ("form", "Complete Form"),
                            ("review", "Manual Review"),
                            ("meeting", "Schedule Meeting"),
                            ("approval", "Approval Required"),
                            ("other", "Other"),
                        ],
                        help_text="Type of task",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="Current task status",
                        max_length=20,
                    ),
                ),
                ("step_number", models.IntegerField(help_text="Order of this task in the onboarding process")),
                (
                    "is_required",
                    models.BooleanField(default=True, help_text="Is this task required for onboarding completion?"),
                ),
                (
                    "assigned_to_client",
                    models.BooleanField(default=False, help_text="Is this task assigned to the client to complete?"),
                ),
                ("due_date", models.DateField(blank=True, help_text="Due date for this task", null=True)),
                ("completed_at", models.DateTimeField(blank=True, help_text="When task was completed", null=True)),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, help_text="Has reminder been sent for this task?"),
                ),
                (
                    "last_reminder_sent_at",
                    models.DateTimeField(blank=True, help_text="When last reminder was sent", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="Task notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who completed this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_onboarding_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task that must be completed before this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_tasks",
                        to="onboarding.onboardingtask",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        help_text="Onboarding process this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="onboarding.onboardingprocess",
                    ),
                ),
                (
                    "related_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document collected for this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_tasks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_tasks",
                "ordering": ["process", "step_number"],
            },
        ),
        migrations.AddField(
            model_name="onboardingprocess",
            name="template",
            field=models.ForeignKey(
                help_text="Template this process is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processes",
                to="onboarding.onboardingtemplate",
            ),
        ),
        migrations.CreateModel(
            name="OnboardingDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_name", models.CharField(help_text="Name of required document", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Description of what's needed")),
                (
                    "document_type",
                    models.CharField(
                        blank=True, help_text="Type of document (e.g., 'W9', 'Operating Agreement')", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("requested", "Requested from Client"),
                            ("received", "Received"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected - Needs Update"),
                        ],
                        default="required",
                        help_text="Document collection status",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True, help_text="Is this document required?")),
                (
                    "requested_at",
                    models.DateTimeField(blank=True, help_text="When document was requested from client", null=True),
                ),
                ("received_at", models.DateTimeField(blank=True, help_text="When document was received", null=True)),
                ("approved_at", models.DateTimeField(blank=True, help_text="When document was approved", null=True)),
                ("review_notes", models.TextField(blank=True, help_text="Review notes (e.g., rejection reason)")),
                ("reminder_count", models.IntegerField(default=0, help_text="Number of reminders sent")),
                (
                    "last_reminder_sent_at",
                    models.DateTimeField(blank=True, help_text="When last reminder was sent", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Uploaded document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_document_links",
                        to="documents.document",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        help_text="Onboarding process this document is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="onboarding.onboardingprocess",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who reviewed this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_onboarding_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related onboarding task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_requirements",
                        to="onboarding.onboardingtask",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_documents",
                "ordering": ["process", "document_name"],
            },
        ),
        migrations.AddIndex(
            model_name="onboardingtemplate",
            index=models.Index(fields=["firm", "status"], name="onboard_tmpl_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingtemplate",
            index=models.Index(fields=["firm", "service_type"], name="onboarding_fir_ser_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingtask",
            index=models.Index(fields=["process", "status"], name="onboard_task_pro_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingtask",
            index=models.Index(fields=["process", "step_number"], name="onboarding_pro_ste_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingtask",
            index=models.Index(fields=["status", "due_date"], name="onboarding_sta_due_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingtask",
            index=models.Index(fields=["assigned_to_client", "status"], name="onboard_task_ass_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingprocess",
            index=models.Index(fields=["firm", "status"], name="onboard_proc_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingprocess",
            index=models.Index(fields=["firm", "-created_at"], name="onboarding_fir_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingprocess",
            index=models.Index(fields=["client", "-created_at"], name="onboarding_cli_cre_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingprocess",
            index=models.Index(fields=["assigned_to", "status"], name="onboard_proc_ass_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingdocument",
            index=models.Index(fields=["process", "status"], name="onboarding_doc_pro_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingdocument",
            index=models.Index(fields=["status", "is_required"], name="onboarding_sta_is__idx"),
        ),
    ]
