# Generated by Django 4.2.17 on 2026-01-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0008_contact_engagementline_and_more"),
        ("finance", "0011_chargeback_paymentfailure_stripewebhookevent_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingOAuthConnection",
            fields=[
                ("connection_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("quickbooks", "QuickBooks Online"), ("xero", "Xero")],
                        help_text="Accounting provider",
                        max_length=20,
                    ),
                ),
                ("access_token", models.TextField(blank=True, help_text="Encrypted OAuth access token")),
                ("refresh_token", models.TextField(blank=True, help_text="Encrypted OAuth refresh token")),
                (
                    "token_expires_at",
                    models.DateTimeField(blank=True, help_text="When access token expires", null=True),
                ),
                ("scopes", models.JSONField(blank=True, default=list, help_text="OAuth scopes granted")),
                (
                    "provider_company_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider company/organization ID (QuickBooks: realmId, Xero: tenantId)",
                        max_length=255,
                    ),
                ),
                (
                    "provider_company_name",
                    models.CharField(
                        blank=True, help_text="Name of the connected company in the accounting system", max_length=255
                    ),
                ),
                (
                    "provider_metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional provider-specific metadata"),
                ),
                ("sync_enabled", models.BooleanField(default=True, help_text="Whether automatic sync is enabled")),
                (
                    "invoice_sync_enabled",
                    models.BooleanField(default=True, help_text="Sync invoices to accounting system"),
                ),
                (
                    "payment_sync_enabled",
                    models.BooleanField(default=True, help_text="Sync payments from accounting system"),
                ),
                (
                    "customer_sync_enabled",
                    models.BooleanField(default=True, help_text="Sync customers/contacts bidirectionally"),
                ),
                (
                    "last_invoice_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful invoice sync timestamp", null=True),
                ),
                (
                    "last_payment_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful payment sync timestamp", null=True),
                ),
                (
                    "last_customer_sync_at",
                    models.DateTimeField(blank=True, help_text="Last successful customer sync timestamp", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired (Token Refresh Needed)"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="active",
                        help_text="Connection status",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="Last error message if status=error")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this connection belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_oauth_connections",
                        to="firm.firm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Staff user who owns this connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_oauth_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounting_oauth_connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSyncMapping",
            fields=[
                ("mapping_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.CharField(help_text="Invoice ID in external accounting system", max_length=255)),
                (
                    "external_number",
                    models.CharField(
                        blank=True, help_text="Invoice number in external accounting system", max_length=100
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True, help_text="Last sync timestamp")),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("synced", "Synced"), ("pending", "Pending Sync"), ("error", "Sync Error")],
                        default="synced",
                        help_text="Current sync status",
                        max_length=20,
                    ),
                ),
                ("sync_error", models.TextField(blank=True, help_text="Error message if sync failed")),
                (
                    "external_metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional metadata from external system"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        help_text="Accounting connection used",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_mappings",
                        to="accounting_integrations.accountingoauthconnection",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this mapping belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_sync_mappings",
                        to="firm.firm",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Internal invoice",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_sync_mappings",
                        to="finance.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_invoice_sync_mappings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["firm", "invoice"], name="accounting__firm_id_14538c_idx"),
                    models.Index(fields=["connection", "external_id"], name="accounting__connect_472932_idx"),
                    models.Index(fields=["firm", "sync_status"], name="accounting__firm_id_0068d6_idx"),
                ],
                "unique_together": {("connection", "invoice")},
            },
        ),
        migrations.CreateModel(
            name="CustomerSyncMapping",
            fields=[
                ("mapping_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    models.CharField(help_text="Customer/Contact ID in external accounting system", max_length=255),
                ),
                (
                    "external_name",
                    models.CharField(
                        blank=True, help_text="Customer/Contact name in external accounting system", max_length=255
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True, help_text="Last sync timestamp")),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("synced", "Synced"), ("pending", "Pending Sync"), ("error", "Sync Error")],
                        default="synced",
                        help_text="Current sync status",
                        max_length=20,
                    ),
                ),
                ("sync_error", models.TextField(blank=True, help_text="Error message if sync failed")),
                (
                    "external_metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional metadata from external system"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Internal client",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_sync_mappings",
                        to="clients.client",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        help_text="Accounting connection used",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_mappings",
                        to="accounting_integrations.accountingoauthconnection",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm this mapping belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_sync_mappings",
                        to="firm.firm",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_customer_sync_mappings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["firm", "client"], name="accounting__firm_id_f98470_idx"),
                    models.Index(fields=["connection", "external_id"], name="accounting__connect_3daba1_idx"),
                    models.Index(fields=["firm", "sync_status"], name="accounting__firm_id_175333_idx"),
                ],
                "unique_together": {("connection", "client")},
            },
        ),
        migrations.AddIndex(
            model_name="accountingoauthconnection",
            index=models.Index(fields=["firm", "user", "provider"], name="accounting__firm_id_bdc83f_idx"),
        ),
        migrations.AddIndex(
            model_name="accountingoauthconnection",
            index=models.Index(fields=["firm", "status"], name="accounting__firm_id_3a380e_idx"),
        ),
        migrations.AddIndex(
            model_name="accountingoauthconnection",
            index=models.Index(fields=["provider", "status"], name="accounting__provide_020e7b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="accountingoauthconnection",
            unique_together={("firm", "provider")},
        ),
    ]
