# Generated by Django 4.2.17 on 2026-01-01 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0008_contact_engagementline_and_more"),
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        ("delivery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("work_item_template_node", "WorkItemTemplateNode"),
                            ("delivery_template", "DeliveryTemplate"),
                            ("engagement_line", "EngagementLine"),
                            ("engagement", "Engagement"),
                        ],
                        help_text="What object type this recurrence applies to",
                        max_length=50,
                    ),
                ),
                (
                    "anchor_type",
                    models.CharField(
                        choices=[("calendar", "Calendar"), ("fiscal", "Fiscal"), ("custom", "Custom")],
                        default="calendar",
                        help_text="Calendar anchoring type",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        help_text="Recurrence frequency",
                        max_length=20,
                    ),
                ),
                ("interval", models.IntegerField(default=1, help_text="Interval for frequency (e.g., every 2 weeks)")),
                (
                    "by_day",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days of week for weekly rules (e.g., ['MON', 'WED', 'FRI'])",
                    ),
                ),
                (
                    "by_month_day",
                    models.JSONField(
                        blank=True, default=list, help_text="Days of month for monthly rules (e.g., [1, 15, -1])"
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(blank=True, help_text="Time of day for deadlines/appointments", null=True),
                ),
                (
                    "timezone",
                    models.CharField(help_text="IANA timezone (required; e.g., 'America/New_York')", max_length=100),
                ),
                (
                    "dst_ambiguous_policy",
                    models.CharField(
                        choices=[("first", "First Occurrence"), ("second", "Second Occurrence")],
                        default="first",
                        help_text="Policy for ambiguous times during DST fall-back",
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField(help_text="When this recurrence starts (timezone-aware)")),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, help_text="When this recurrence ends (optional; open-ended if null)", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused"), ("canceled", "Canceled")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("paused_at", models.DateTimeField(blank=True, help_text="When this rule was paused", null=True)),
                ("canceled_at", models.DateTimeField(blank=True, help_text="When this rule was canceled", null=True)),
                ("name", models.CharField(help_text="Human-readable name for this recurrence rule", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Description of this recurrence")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canceled_recurrence_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recurrence_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        help_text="Firm (workspace) this recurrence rule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_rules",
                        to="firm.firm",
                    ),
                ),
                (
                    "paused_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paused_recurrence_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_delivery_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_rules",
                        to="delivery.deliverytemplate",
                    ),
                ),
                (
                    "target_engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_rules",
                        to="clients.clientengagement",
                    ),
                ),
                (
                    "target_engagement_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_rules",
                        to="clients.engagementline",
                    ),
                ),
            ],
            options={
                "db_table": "recurrence_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurrenceGeneration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "period_key",
                    models.CharField(
                        help_text="Stable period key (e.g., '2026-01', '2026-Q1', '2026-W05')", max_length=100
                    ),
                ),
                (
                    "period_starts_at",
                    models.DateTimeField(help_text="Period start (UTC, derived from timezone-aware boundaries)"),
                ),
                (
                    "period_ends_at",
                    models.DateTimeField(help_text="Period end (UTC, derived from timezone-aware boundaries)"),
                ),
                (
                    "period_label",
                    models.CharField(
                        blank=True, help_text="Human-friendly label (e.g., 'January 2026')", max_length=100
                    ),
                ),
                (
                    "target_object_type",
                    models.CharField(
                        choices=[("work_item", "WorkItem"), ("task", "Task"), ("appointment", "Appointment")],
                        help_text="Type of object created by this generation",
                        max_length=50,
                    ),
                ),
                (
                    "target_object_id",
                    models.IntegerField(
                        blank=True, help_text="ID of created object (nullable until generated)", null=True
                    ),
                ),
                (
                    "target_discriminator",
                    models.CharField(
                        blank=True,
                        help_text="Discriminator for multiple targets per period (e.g., template_node_id)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("generated", "Generated"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(blank=True, help_text="When the target object was generated", null=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Hash of (tenant + rule + period + discriminator) for idempotency",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "skip_reason_code",
                    models.CharField(
                        blank=True, help_text="Reason code if skipped (e.g., 'engagement_not_active')", max_length=50
                    ),
                ),
                ("skip_reason_message", models.TextField(blank=True, help_text="Human-readable reason if skipped")),
                ("error_summary", models.TextField(blank=True, help_text="Redacted error summary if failed")),
                ("attempt_count", models.IntegerField(default=0, help_text="Number of generation attempts")),
                (
                    "last_attempt_at",
                    models.DateTimeField(blank=True, help_text="When the last generation attempt occurred", null=True),
                ),
                (
                    "backfilled",
                    models.BooleanField(
                        default=False, help_text="Whether this generation was created via backfill operation"
                    ),
                ),
                ("backfill_reason", models.TextField(blank=True, help_text="Reason for backfill (if backfilled=True)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, help_text="Correlation ID for tracking", max_length=64),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_generations",
                        to="firm.firm",
                    ),
                ),
                (
                    "recurrence_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generations",
                        to="recurrence.recurrencerule",
                    ),
                ),
            ],
            options={
                "db_table": "recurrence_generation",
                "ordering": ["-period_starts_at"],
            },
        ),
        migrations.AddIndex(
            model_name="recurrencerule",
            index=models.Index(fields=["firm", "status"], name="recurrence_rul_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencerule",
            index=models.Index(fields=["firm", "scope"], name="recurrence_fir_sco_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencerule",
            index=models.Index(fields=["target_delivery_template"], name="recurrence_tar_del_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencerule",
            index=models.Index(fields=["target_engagement"], name="recurrence_tar_eng_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencerule",
            index=models.Index(fields=["target_engagement_line"], name="recurrence_tar_lin_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencerule",
            index=models.Index(fields=["start_at"], name="recurrence_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencerule",
            index=models.Index(fields=["end_at"], name="recurrence_end_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencegeneration",
            index=models.Index(
                fields=["firm", "recurrence_rule", "-period_starts_at"], name="recurrence_fir_rec_per_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurrencegeneration",
            index=models.Index(fields=["firm", "status"], name="recurrence_gen_fir_sta_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencegeneration",
            index=models.Index(fields=["idempotency_key"], name="recurrence_ide_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencegeneration",
            index=models.Index(fields=["target_object_type", "target_object_id"], name="recurrence_tar_tar_idx"),
        ),
        migrations.AddIndex(
            model_name="recurrencegeneration",
            index=models.Index(fields=["correlation_id"], name="recurrence_cor_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recurrencegeneration",
            unique_together={("recurrence_rule", "period_key", "target_discriminator")},
        ),
    ]
