# Generated by Django 4.2.8 on 2025-12-23 12:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("primary_contact_name", models.CharField(max_length=255)),
                ("primary_contact_email", models.EmailField(max_length=254)),
                ("primary_contact_phone", models.CharField(blank=True, max_length=50)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="USA", max_length=100)),
                ("website", models.URLField(blank=True)),
                ("employee_count", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive - No Active Projects"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "portal_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether client portal access is enabled",
                    ),
                ),
                (
                    "total_lifetime_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue from this client across all engagements",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "active_projects_count",
                    models.IntegerField(
                        default=0, help_text="Number of currently active projects"
                    ),
                ),
                (
                    "client_since",
                    models.DateField(help_text="Date of first engagement"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to client)"
                    ),
                ),
            ],
            options={
                "db_table": "clients_client",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientChatThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date of this thread (YYYY-MM-DD)"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active thread",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="When this thread was archived", null=True
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(
                        default=0, help_text="Total messages in this thread"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of last message", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clients_chat_thread",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ClientComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "has_attachment",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this comment has file attachments",
                    ),
                ),
                (
                    "is_read_by_firm",
                    models.BooleanField(
                        default=False,
                        help_text="Whether firm team has read this client comment",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the comment was read by firm",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clients_comment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientPortalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Client Admin"),
                            ("member", "Client Member"),
                            ("viewer", "View Only"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("can_upload_documents", models.BooleanField(default=True)),
                ("can_view_billing", models.BooleanField(default=True)),
                ("can_message_team", models.BooleanField(default=True)),
                ("can_view_projects", models.BooleanField(default=True)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_users",
                        to="clients.client",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="Firm user who invited this client user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_portal_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_portal_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clients_portal_user",
                "ordering": ["-invited_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Pinned notes appear at top"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_client_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_notes",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "clients_note",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_from_client",
                    models.BooleanField(
                        default=False,
                        help_text="Whether sender is a client portal user",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("file", "File Attachment"),
                            ("system", "System Notification"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message text content")),
                (
                    "attachment_url",
                    models.URLField(
                        blank=True,
                        help_text="S3 URL for file attachment (if message_type=file)",
                    ),
                ),
                (
                    "attachment_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original filename of attachment",
                        max_length=255,
                    ),
                ),
                (
                    "attachment_size_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether message has been read by recipient",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When message was read", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who read this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_client_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_client_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="Thread this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="clients.clientchatthread",
                    ),
                ),
            ],
            options={
                "db_table": "clients_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Current Engagement"),
                            ("completed", "Completed"),
                            ("renewed", "Renewed"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version number for this engagement (1, 2, 3...)",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual completion date if different from planned",
                        null=True,
                    ),
                ),
                (
                    "contracted_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "actual_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actual revenue generated (may differ from contracted)",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "clients_engagement",
                "ordering": ["-start_date"],
            },
        ),
    ]
