# Generated by Django 4.2.8 on 2025-12-24 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientengagement",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_engagements",
                to="crm.contract",
            ),
        ),
        migrations.AddField(
            model_name="clientengagement",
            name="parent_engagement",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous engagement if this is a renewal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewals",
                to="clients.clientengagement",
            ),
        ),
        migrations.AddField(
            model_name="clientcomment",
            name="author",
            field=models.ForeignKey(
                help_text="Portal user who wrote this comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_task_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientcomment",
            name="client",
            field=models.ForeignKey(
                help_text="Client who owns this comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_comments",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="clientcomment",
            name="read_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Firm team member who read this comment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="read_client_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
