# Generated by Django 4.2.8 on 2025-12-23 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("projects", "0001_initial"),
        ("clients", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcomment",
            name="task",
            field=models.ForeignKey(
                help_text="Task being commented on",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_comments",
                to="projects.task",
            ),
        ),
        migrations.AddField(
            model_name="clientchatthread",
            name="client",
            field=models.ForeignKey(
                help_text="Client this thread belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_threads",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="clientchatthread",
            name="last_message_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who sent last message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_chat_message_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="account_manager",
            field=models.ForeignKey(
                help_text="Primary account manager for this client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="assigned_team",
            field=models.ManyToManyField(
                blank=True,
                help_text="Team members assigned to this client",
                related_name="assigned_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="source_proposal",
            field=models.ForeignKey(
                blank=True,
                help_text="The proposal that created this client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_clients",
                to="crm.proposal",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="source_prospect",
            field=models.ForeignKey(
                blank=True,
                help_text="The prospect that was converted to this client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_clients",
                to="crm.prospect",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientportaluser",
            unique_together={("client", "user")},
        ),
        migrations.AddIndex(
            model_name="clientnote",
            index=models.Index(
                fields=["client", "-created_at"], name="clients_not_client__6ec79c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="clients_mes_thread__be1267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientmessage",
            index=models.Index(
                fields=["sender", "-created_at"], name="clients_mes_sender__5a8927_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientmessage",
            index=models.Index(
                fields=["is_read"], name="clients_mes_is_read_2bc49f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientengagement",
            index=models.Index(
                fields=["client", "-start_date"], name="clients_eng_client__bb936e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientengagement",
            index=models.Index(fields=["status"], name="clients_eng_status_060f27_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="clientengagement",
            unique_together={("client", "version")},
        ),
        migrations.AddIndex(
            model_name="clientcomment",
            index=models.Index(
                fields=["task", "-created_at"], name="clients_com_task_id_2cb3d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcomment",
            index=models.Index(
                fields=["client", "-created_at"], name="clients_com_client__faa6ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcomment",
            index=models.Index(
                fields=["is_read_by_firm"], name="clients_com_is_read_539f87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientchatthread",
            index=models.Index(
                fields=["client", "-date"], name="clients_cha_client__3b55f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientchatthread",
            index=models.Index(
                fields=["is_active"], name="clients_cha_is_acti_37f1b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientchatthread",
            index=models.Index(
                fields=["-last_message_at"], name="clients_cha_last_me_df0c77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientchatthread",
            unique_together={("client", "date")},
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["status"], name="clients_cli_status_ce0d15_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["account_manager"], name="clients_cli_account_68005b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["company_name"], name="clients_cli_company_9dfa94_idx"
            ),
        ),
    ]
