# Generated by Django 4.2.8 on 2025-12-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcomment",
            name="is_purged",
            field=models.BooleanField(
                default=False, help_text="Whether this comment content has been purged"
            ),
        ),
        migrations.AddField(
            model_name="clientcomment",
            name="purge_reason",
            field=models.TextField(
                blank=True, help_text="Reason for purging this comment"
            ),
        ),
        migrations.AddField(
            model_name="clientcomment",
            name="purged_at",
            field=models.DateTimeField(
                blank=True, help_text="When this comment was purged", null=True
            ),
        ),
        migrations.AddField(
            model_name="clientcomment",
            name="purged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who purged this comment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purged_client_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientmessage",
            name="is_purged",
            field=models.BooleanField(
                default=False, help_text="Whether this message content has been purged"
            ),
        ),
        migrations.AddField(
            model_name="clientmessage",
            name="purge_reason",
            field=models.TextField(
                blank=True, help_text="Reason for purging this message"
            ),
        ),
        migrations.AddField(
            model_name="clientmessage",
            name="purged_at",
            field=models.DateTimeField(
                blank=True, help_text="When this message was purged", null=True
            ),
        ),
        migrations.AddField(
            model_name="clientmessage",
            name="purged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who purged this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purged_client_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
