# Generated by Django 4.2.8 on 2025-12-25 09:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("firm", "0004_auditevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0005_rename_clients_cli_org_idx_clients_cli_organiz_c54e76_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="autopay_activated_at",
            field=models.DateTimeField(blank=True, help_text="When autopay was enabled", null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="autopay_activated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who enabled autopay",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="autopay_activations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="autopay_enabled",
            field=models.BooleanField(default=False, help_text="Enable automatic payment of invoices"),
        ),
        migrations.AddField(
            model_name="client",
            name="autopay_payment_method_id",
            field=models.CharField(blank=True, help_text="Stripe payment method ID for autopay", max_length=255),
        ),
        migrations.AddField(
            model_name="clientengagement",
            name="allow_hourly_billing",
            field=models.BooleanField(default=False, help_text="Allow hourly billing for this engagement"),
        ),
        migrations.AddField(
            model_name="clientengagement",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                help_text="Firm this engagement belongs to (auto-populated from client)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_engagements",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="clientengagement",
            name="hourly_rate_default",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default hourly rate (if hourly billing allowed)",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="clientengagement",
            name="package_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed package fee (required for package/mixed mode)",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="clientengagement",
            name="package_fee_schedule",
            field=models.CharField(
                blank=True, help_text="Payment schedule (e.g., 'Monthly', 'Quarterly', 'One-time')", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="clientengagement",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("package", "Package/Fixed Fee"),
                    ("hourly", "Hourly/Time & Materials"),
                    ("mixed", "Mixed (Package + Hourly)"),
                ],
                default="package",
                help_text="Pricing model for this engagement",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="clientengagement",
            index=models.Index(fields=["firm", "status"], name="clients_eng_firm_id_76f423_idx"),
        ),
        migrations.AddIndex(
            model_name="clientengagement",
            index=models.Index(fields=["firm", "-start_date"], name="clients_eng_firm_id_855b74_idx"),
        ),
    ]
