# Generated by Django 4.2.17 on 2026-01-01 04:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modules.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("firm", "0013_remove_provisioninglog_firm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0007_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(help_text="Contact's first name", max_length=100)),
                ("last_name", models.CharField(help_text="Contact's last name", max_length=100)),
                ("email", models.EmailField(help_text="Contact's email address", max_length=254)),
                ("phone", models.CharField(blank=True, help_text="Contact's phone number", max_length=50)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, help_text="Contact's mobile phone number", max_length=50),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, help_text="Job title at the client organization", max_length=200),
                ),
                (
                    "department",
                    models.CharField(blank=True, help_text="Department within the organization", max_length=100),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(default=False, help_text="Whether this is the primary contact for the client"),
                ),
                (
                    "can_approve_invoices",
                    models.BooleanField(default=False, help_text="Can approve invoices on behalf of client"),
                ),
                (
                    "receives_billing_emails",
                    models.BooleanField(default=False, help_text="Receives billing-related emails"),
                ),
                (
                    "receives_project_updates",
                    models.BooleanField(default=True, help_text="Receives project update notifications"),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone"), ("sms", "SMS"), ("portal", "Portal")],
                        default="email",
                        help_text="Preferred method of contact",
                        max_length=20,
                    ),
                ),
                (
                    "opt_out_marketing",
                    models.BooleanField(default=False, help_text="Opted out of marketing communications"),
                ),
                ("opt_out_sms", models.BooleanField(default=False, help_text="Opted out of SMS communications")),
                ("is_active", models.BooleanField(default=True, help_text="Whether this contact is active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, help_text="Internal notes about this contact")),
            ],
            options={
                "db_table": "clients_contact",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EngagementLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_number", models.IntegerField(help_text="Line number within the engagement (1, 2, 3...)")),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("product", "Product"),
                            ("deliverable", "Deliverable"),
                            ("retainer", "Retainer"),
                            ("milestone", "Milestone"),
                            ("other", "Other"),
                        ],
                        default="service",
                        help_text="Type of line",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(help_text="Description of this line item", max_length=500)),
                ("detailed_description", models.TextField(blank=True, help_text="Detailed description or scope")),
                ("service_code", models.CharField(blank=True, help_text="Service or product code", max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Quantity (hours, units, etc.)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price (quantity * unit_price)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount percentage (0-100)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount amount (calculated from discount_percent or manual)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net amount after discount (total_price - discount_amount)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("start_date", models.DateField(blank=True, help_text="When work on this line starts", null=True)),
                ("end_date", models.DateField(blank=True, help_text="When work on this line ends", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of this line",
                        max_length=20,
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Completion percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "delivery_template_code",
                    models.CharField(blank=True, help_text="Delivery template code (if applicable)", max_length=100),
                ),
                (
                    "is_billable",
                    models.BooleanField(default=True, help_text="Whether this line is billable to the client"),
                ),
                (
                    "invoice_schedule",
                    models.CharField(
                        blank=True,
                        help_text="Invoice schedule (e.g., 'Monthly', 'Upon Completion', 'Milestone')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, help_text="Internal notes about this line")),
            ],
            options={
                "db_table": "clients_engagement_line",
                "ordering": ["engagement", "line_number"],
            },
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="clients_client_org_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="clients_client_autopay_idx",
        ),
        migrations.RemoveIndex(
            model_name="clientengagement",
            name="clients_eng_client_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="clientengagement",
            name="clients_eng_pricing_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="clients_org_visibility_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_acc_idx",
            old_name="clients_cli_account_68005b_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_com_idx",
            old_name="clients_cli_company_9dfa94_idx",
        ),
        migrations.RenameIndex(
            model_name="clientchatthread",
            new_name="clients_cli_dat_idx",
            old_name="clients_cha_client__3b55f3_idx",
        ),
        migrations.RenameIndex(
            model_name="clientchatthread",
            new_name="clients_thr_is_act_idx",
            old_name="clients_cha_is_acti_37f1b9_idx",
        ),
        migrations.RenameIndex(
            model_name="clientchatthread",
            new_name="clients_las_idx",
            old_name="clients_cha_last_me_df0c77_idx",
        ),
        migrations.RenameIndex(
            model_name="clientcomment",
            new_name="clients_tas_cre_idx",
            old_name="clients_com_task_id_2cb3d4_idx",
        ),
        migrations.RenameIndex(
            model_name="clientcomment",
            new_name="clients_com_cli_cre_idx",
            old_name="clients_com_client__faa6ef_idx",
        ),
        migrations.RenameIndex(
            model_name="clientcomment",
            new_name="clients_com_is_rea_idx",
            old_name="clients_com_is_read_539f87_idx",
        ),
        migrations.RenameIndex(
            model_name="clientengagement",
            new_name="clients_cli_sta_idx",
            old_name="clients_eng_client__bb936e_idx",
        ),
        migrations.RenameIndex(
            model_name="clientengagement",
            new_name="clients_sta_idx",
            old_name="clients_eng_status_060f27_idx",
        ),
        migrations.RenameIndex(
            model_name="clientmessage",
            new_name="clients_thr_cre_idx",
            old_name="clients_mes_thread__be1267_idx",
        ),
        migrations.RenameIndex(
            model_name="clientmessage",
            new_name="clients_sen_cre_idx",
            old_name="clients_mes_sender__5a8927_idx",
        ),
        migrations.RenameIndex(
            model_name="clientmessage",
            new_name="clients_msg_is_rea_idx",
            old_name="clients_mes_is_read_2bc49f_idx",
        ),
        migrations.RenameIndex(
            model_name="clientnote",
            new_name="clients_not_cli_cre_idx",
            old_name="clients_not_client__6ec79c_idx",
        ),
        migrations.AddField(
            model_name="client",
            name="consent_source",
            field=models.CharField(
                blank=True,
                help_text="Source of consent (e.g., 'signup_form', 'email_campaign', 'portal_settings')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="consent_timestamp",
            field=models.DateTimeField(blank=True, help_text="When consent was given (GDPR requirement)", null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="marketing_opt_in",
            field=models.BooleanField(
                default=False, help_text="Has the client opted in to receive marketing communications?"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="retainer_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current retainer balance (prepaid hours/amount)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="retainer_hours_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), help_text="Prepaid hours remaining in retainer", max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="retainer_last_updated",
            field=models.DateTimeField(blank=True, help_text="When retainer balance was last updated", null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="tos_accepted",
            field=models.BooleanField(default=False, help_text="Has the client accepted Terms of Service?"),
        ),
        migrations.AddField(
            model_name="client",
            name="tos_accepted_at",
            field=models.DateTimeField(blank=True, help_text="When Terms of Service were accepted", null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="tos_version",
            field=models.CharField(blank=True, help_text="Version of ToS that was accepted", max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="client",
            name="website",
            field=models.URLField(blank=True, validators=[modules.core.validators.validate_safe_url]),
        ),
        migrations.AddField(
            model_name="engagementline",
            name="engagement",
            field=models.ForeignKey(
                help_text="Parent engagement this line belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="clients.clientengagement",
            ),
        ),
        migrations.AddField(
            model_name="engagementline",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                help_text="Firm this engagement line belongs to (auto-populated from engagement)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagement_lines",
                to="firm.firm",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="client",
            field=models.ForeignKey(
                help_text="Client this contact belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this contact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="portal_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated portal user account (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_profile",
                to="clients.clientportaluser",
            ),
        ),
        migrations.AddIndex(
            model_name="engagementline",
            index=models.Index(fields=["firm", "engagement"], name="clients_engline_frm_eng_idx"),
        ),
        migrations.AddIndex(
            model_name="engagementline",
            index=models.Index(fields=["engagement", "line_number"], name="clients_engline_eng_lnum_idx"),
        ),
        migrations.AddIndex(
            model_name="engagementline",
            index=models.Index(fields=["engagement", "status"], name="clients_engline_eng_stat_idx"),
        ),
        migrations.AddIndex(
            model_name="engagementline",
            index=models.Index(fields=["service_code"], name="clients_engline_svc_idx"),
        ),
        migrations.AddIndex(
            model_name="engagementline",
            index=models.Index(fields=["delivery_template_code"], name="clients_engline_tpl_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="engagementline",
            unique_together={("engagement", "line_number")},
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["client", "is_active"], name="clients_contact_cli_act_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["client", "is_primary_contact"], name="clients_contact_cli_pri_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="clients_contact_email_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["phone"], name="clients_contact_phone_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("client", "email")},
        ),
    ]
