# Generated by ChatGPT on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0013_email_opt_in_and_unsubscribe_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, help_text="City for this contact", max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="country",
            field=models.CharField(blank=True, help_text="Country for this contact", max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude for geographic filtering",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude for geographic filtering",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(blank=True, help_text="Postal or ZIP code for this contact", max_length=20),
        ),
        migrations.AddField(
            model_name="contact",
            name="state",
            field=models.CharField(blank=True, help_text="State or province for this contact", max_length=100),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["country"], name="clients_contact_country_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["state"], name="clients_contact_state_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["city"], name="clients_contact_city_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["postal_code"], name="clients_contact_postal_idx"),
        ),
    ]
